### ISSUE TITLE
Optimize Github Actions workflows

### ISSUE THREAD

**Issue by leventozen** [Trendyol/baklava#124]
We are using `npm ci` to install all the dependencies. It uses only package lock file, so npm can skip the first steps (you can find more detailed information [here](https://docs.npmjs.com/cli/v7/commands/npm-ci)). It does clean install, in other words deletes `node_modules`. However, we can cache `~/.npm` to prevent redownloading all this stuff.

**Comment by muratcorlu** [comment]
@leventozen can we consider this done with #152 ?
