### ISSUE TITLE
Dialog Component

### ISSUE THREAD

**Issue by muratcorlu** [Trendyol/baklava#137]
## Design

[Figma](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?node-id=1992%3A8280)

## Implementation

General usage example:

```html 
<bl-dialog caption='Dialog Title'>
      <p> Dialog Content </p>
      <bl-button slot="primary-action">Save Message</bl-button>
      <bl-button slot="secondary-action" kind="danger">Delete Message</bl-button>
      <bl-button slot="tertiary-action">Dismiss</bl-button>
</bl-dialog>
```

### Rules

* By default a dialog contains a close button and a primary action button.
* Dialogs are always closeable. By default it closes by close button, by clicking outside of the dialog and by clicking "esc" on keyboard.
* A dialog should contain at least one content (text, image etc.).
* Dialogs are always centered on the page, with an overlay behind them that hides the page content.
* Only large buttons can be used in the action bar and there can be maximum 3 buttons (primary, secondary and tertiary).

#### Attributes

| Attribute | Description | Default Value |
| --------------- | --------------- | --------------- |
| caption (`string`) | Title of the dialog | - |
| open (`boolean`) | Sets dialog open-close status. By default, the dialog is closed.	 | false |

#### Slots

| Name | Description | Default Content |
| --------------- | --------------- | --------------- |
| `default` slot | Content of dialog | - |
| `actions` slot | Dialog actions (action buttons) of dialog | - |

#### Events

| Event | Description |
| --------------- | --------------- |
| `bl-dialog-open` | Will be triggered every time the dialog is opened |
| `bl-dialog-close` | Will be triggered every time the dialog is closed |

**Comment by muratcorlu** [comment]
### Dialog Component Design Meeting Report

Date: 20.09.2022 14:00 (UTC+3)
Attendees: @buseselvi  @muratcorlu @leventozen @stovein 

* There will be no `size` variant of the dialog, instead we'll decide `min/max - height/width` values and dialog will be fluidly sized regarding to it's content within those values.
* Dialogs will be only in modal mode for now (with backdrop and blocking)
* Positioning can be different on desktop and handheld screens to increase usability. We considered to use dialog on bottom on handheld device to make action buttons more reachable.
* Dialog will be dismissed by clicking backdrop or pressing Esc.
* Dialog will be always "closable" for now. If we see a common use case for "non-closable" (only can be closed by using an action button, programmatically) we'll consider adding this feature in the future.
* We'll define default order and rules for action buttons. Like
   * Dialog can not have more than one primary action.
   * Dialog can have up to 3 actions. (primary, secondary, tertiary) We'll map those actions with related button variant.
* We'll define a default caption and text style. But Dialog content will be freely stylable.

After design work, we'll start implementation design and update this issue with it.

**Comment by yessGlory17** [comment]
Do you want some help? @muratcorlu

**Comment by olkeoguz** [comment]
We need to decide what to do in case of
* not having  at least one button and one text content,
* having more than 3 action buttons,
* having more than one primary, secondary or tertiary button,
* how to handle lazy loading for the dialog as it always stays on the dom.

**Comment by leventozen** [comment]
> We need to decide what to do in case of
> 
> * not having at least one button and one text content,
> * having more than 3 action buttons,
> * having more than one primary, secondary or tertiary button,
> * how to handle lazy loading for the dialog as it always stays on the dom.

If there is no button provided, content rendered and vice versa, programatically. Is it should be a case? Additionally, we have primary, secondary and tertiary actions/buttons in our dialog, so there will be no other buttons. If there is no primary button, this means, there won't be secondary and tertiary buttons, too.

- Not have more than 3 action buttons
- Not have more than one primary, secondary or tertiary buttons. (If there is a use case, we can discuss it)
- For the last part, what do you mean by lazy loading?

**Comment by DamlaDemir** [comment]
The first option made more sense to us because;
- we will do fewer controls in the first option.
- the order doesn't matter the user can give any random sequence we will fix them easily in the dialog.

And if there is more than one primary button the first primary button will override right?
