### ISSUE TITLE
Alert Component

### ISSUE THREAD

**Issue by muratcorlu** [Trendyol/baklava#138]
67
[Figma](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?node-id=796%3A7839)

## Implementation

General usage example:

```html 
  <bl-alert
    variant="error"
    caption="Default Caption"
    description="Default Description"
    icon="close_fill"
    closable
  >
    <span slot="caption">
      Awesome Caption!
    </span>
    Some important description.
    <bl-button slot="action">
      Click me!
    </bl-button>
  </bl-alert>
```

### Rules

* `closable` attribute displays a close button in alert component. Emits an event named `bl-close` and component will hide itself via css property.
* Component will not have default icon but users can use `icon` to use default icons according to variants or `icon="calendar"` to customize icon.
* `action` slot will only accept `bl-button` component (else will cause an error) and will override some attributes of the slotted button (`variant` will be `secondary` and `kind` will be `text`, `icon` will not be allowed).
* For mobile design `bl-button` component which can be used in `action` slot will convert itself to icon-only `bl-button`.

### `bl-alert` component

Alert component displays an informational message to users with additional features if desired.

#### Attributes

| Attribute | Description | Default Value |
| --------------- | --------------- | --------------- |
| variant (`string`) | Decides variants of alert box ( `info`, `success`, `warning`, `error` )  | `"info"` |
| caption (`string`) | Sets alert caption  | - |
| description (`string`) | Sets alert description  | - |
| icon (`string, boolean`) | Allows to customize alert icon  | `false` |
| closable (`boolean`) | Displays a close button when used  | `false` |

#### Slots

| Event | Description |
| --------------- | --------------- |
| `caption` slot | Will fill alert caption |
| `default` slot | Will fill alert description |
| `action` slot | Will fill alert action slot and will accept only `bl-button` component or it will throw an error |

#### Events

| Event | Description |
| --------------- | --------------- |
| `bl-close` | Will be triggered each time close button is clicked |

**Comment by muratcorlu** [comment]
- I would go with slots for `title` and `description`. These are the real contents of the alert and using slots is better for setting content.
- Even if we go with attributes, we should avoid using `title` since it's a reserved attribute in HTML and causes to show a tooltip in desktop browser when cursor wait for a while on top of the element. (We noticed this while we implement Tab component)
- We need to use `kebab-case` for attribute names. So instead of `actionLabel` it should be `action-label`.
- Actions can be also considered as slots.
- As a follow-up of my 1st comment, multiple alerts should not be set via a json object. Our web components should be structured with HTML as much as possible. Multiple alert components in a -for example- `alert-group` component or a swiper component would be a better approach.
- Use a CSS custom property to hide default icon instead of `hide-icon` attribute.
- A public `close` method would be helpful to programmatically close/remove the alert.

**Comment by muratcorlu** [comment]
@buseselvi I have some questions about design:

* When you have multiple alerts (paginated) with a close button, if you hit close button, does it close all of the alerts or just current one (current page)?
* Can paginated alerts be in different variants? Like first informational, then next one success etc.
* Does alert variants have default icons?
* Does "Titleless" alert has only description? Or can we say alert always has a title but optionally a description? To be more clear, the text that users will write inside alert in "titleless" mode, will be something like a short title or a longer form text like a description. This can effect technical design decision.

**Comment by buseselvi** [comment]
@muratcorlu 

- Close icon closes the component, so it closes all alerts
- No, it cant be different variants, component stays the same.
- Each variant has different default icons as we show in the design.
- We can say that the "Titleless" alert has only description. Messages are mostly not short, there may be 2-3 sentences like a description. Title is optional.

**Comment by koulgar** [comment]
Thank you all for your feedbacks @muratcorlu @buseselvi,
We've updated issue due to comments. 
- One issue that we couldn't decide weather is it better to use `bl-alert` component and make it communicate with `bl-alert-group` component to hide it's wrapper and such or create an extra completely new component called `bl-alert-item` for multiple message usage to be slotted in `bl-alert-group`.
- Another one is to make inner component (`bl-alert` or follow up to first comment `bl-alert-item`) to prevent rendering of `alert-title` when `alert-description` is not provided.

**Comment by koulgar** [comment]
> * One issue that we couldn't decide weather is it better to use `bl-alert` component and make it communicate with `bl-alert-group` component to hide it's wrapper and such or create an extra completely new component called `bl-alert-item` for multiple message usage to be slotted in `bl-alert-group`. In our opinion current example usage of `bl-alert` increases development complexity. New component such as `bl-alert-item` to be used with `bl-alert-group` actually might be cleaner way to do it.

after a few days of brainstorming we might use `bl-alert-group` for multiple messages like example below;
```
<bl-alert-group variant="warning" closable>
    <bl-alert-item
      alert-title="Default Title"
      alert-description="Default Description"
      alert-icon="close_fill"
      action-href="https://www.trendyol.com"
      action-label="Default click me!"
      action-target="_self"
    ></bl-alert-item>
</bl-alert-group>
```

and for single message usage we can use `bl-alert` component like this;
```
 <bl-alert
    variant="error"
    alert-title="Default Title"
    alert-description="Default Description"
    alert-icon="close_fill"
    action-href="https://www.trendyol.com"
    action-label="Default click me!"
    action-target="_self"
    closable
  ></bl-alert>
```
For this kind of usage `bl-alert` reuses `bl-alert-item` inside, passes some attributes and css variables to `bl-alert-item` to prevent code duplication and act as a shell for `bl-alert-item`. `bl-alert-item` works exactly same for both `bl-alert-group` and `bl-alert`. Those two shell components (`bl-alert-group` & `bl-alert`) has similar features which only separates them that `bl-alert` will not contain `pagination` function and will not contain slots (except `bl-alert-item`'s `title` & `description` slots which will work for both scenerios).

These cases seems like an efficient way to prevent code & functionality duplication & development wise.
Am i missing an obvious or edge case that this not covers? What do you think?

**Comment by muratcorlu** [comment]
To be honest, I'm not convinced about pagination of alerts at all. Especially, combining different types of alerts (success, errors etc) in a group that only has one type of alert looks confusing to me. For example:

```html
<bl-alert-group closable>
  <bl-alert variant="success">Your message sent!</bl-alert>
  <bl-alert variant="error">Something wrong happened. Please try again later.</bl-alert>
</bl-alert-group>
```

In the example above we have 2 alerts that we want to show to the user. One is a success message, other is an error message. Since a paginated alert can only one type of alert, we need to pick a type here for the group. Which one the developer should pick? In any case we'll give a wrong signal to the user about the content of the message. Even more, this can cause the users dismiss some important messages by closing the group since more important message can be in 2nd page.

I couldn't find a similar implementation in other design systems. If we don't feel a strong need about pagination of the alerts, I'll offer to think more on pagination part later and focusing a single alert message first. Does this make sense?

Maybe we can organize a quick meeting on this on this wednesday. @buseselvi @koulgar

**Comment by koulgar** [comment]
> @muratcorlu
> 
> * Close icon closes the component, so it closes all alerts
> * No, it cant be different variants, component stays the same.
> * Each variant has different default icons as we show in the design.
> * We can say that the "Titleless" alert has only description. Messages are mostly not short, there may be 2-3 sentences like a description. Title is optional.

if i'm not mistaken @buseselvi already cleared that variants will not change when messages change by pagination (quoted above) and general usage examples above i've used variants on parent components not on items according to that.

I've also researched for multiple messaged alert component examples in different UI libraries but haven't seen one yet but still i think multiple alert component in design is manageable.

I'm down for a meeting on wednesday to clearing out rocks out of the way. 👍

**Comment by muratcorlu** [comment]
We had a meeting yesterday with @buseselvi, @leventozen, @koulgar and @canerturul. Here is the outcome:

* **We'll remove pagination feature from alert *for now***. Use cases that we could see for pagination is not very clear. Since it adds some confusion and so much complexity to the implementation, we decided to postpone that feature.
* **Action button will be defined as a slot**. Buttons have more features than href and target, and we see user may need to have those features too. Only thing is, we'll override some attributes of the slotted button (`variant` will be `secondary` and `kind` will be `text`, `icon` will not be allowed).
* **Action buttons will be `secondary` button in all variant.** We already have a11y issues about similar colors and for not making this problem deeper here, to have a better contrast, we'll use secondary button.
* **Alert variants doesn't have an icon by default. But if it's needed, some default icons will be provided.** Idea was, by default alerts will not have an icon. But if user just adds an icon attribute without value (`<bl-alert icon>`) then a default icon will be used regarding to current variant. User will also be able to set a custom icon by just setting a value (`<bl-alert icon="calendar">`)
* **At least one of the `title` and `description` fields will be default slot. And other *can* also be another slot.** Slots are easier to write in basic templates, it's better for a11y (they can be red as content), and more flexible for some extra needs (like setting a word bold in the text). We couldn't sharply decide if both should be slots or one of them could be attribute, this default will be clear while implementation.

Issue will be updated regarding to those decisions.

**Comment by koulgar** [comment]
We've updated issue w/@canerturul according to meeting notes. FYI @muratcorlu @leventozen @buseselvi

**Comment by muratcorlu** [comment]
We don’t need `alert-` prefixes for attributes and slot names. @koulgar

**Comment by muratcorlu** [comment]
As an outcome of the discussion we had with @buseselvi and @koulgar, we are now considering to make alert action button visible with it's label on mobile version too. A decision will be done soon by aligning with mobile team.

The concern was about UX of the alert with action on mobile. Hiding alert button label can cause bad user experience since user may not get what will happen when they click to the alert. Also making whole alert component clickable prevents developers to put links inside description text and we are not sure if this is an acceptable limitation.

**Comment by buseselvi** [comment]
We updated the alert view on mobile devices in the design documentation based on the text area (caption and description) width. @koulgar fyi

<img width="1722" alt="image" src="https://user-images.githubusercontent.com/106681486/188651824-8a2ec285-22da-49e4-85b6-81f2e79878bb.png">

**Comment by koulgar** [comment]
@muratcorlu, in first version of design guide component were switching to responsive design 1024px of screen width. Now in new design it seems like switch condition is 300px of component width. First thing comes in my mind that we're gonna need an event listener to bind a class, or using something like `flex-wrap` and `flex-basis`. What would you suggest for a healthier way?

**Comment by muratcorlu** [comment]
@koulgar It's not the container width actually, it's the width of title and description. So you just need to set a `min-width` to wrapper of that 2 element, and if button can not fit to the right, it will go below.

**Comment by koulgar** [comment]
Hey, @buseselvi 
FYI While we're testing responsive design w/ @muratcorlu, @canerturul we've realized that 300px text limit breaks component when device viewport is 325px (which is resolution for devices like Iphone 5 ). In order to fix it we've set text width limit to 200px to be safe. Any width 200px is breaks design for our current design.
- One issue we'd like to clear out is that when description is longer than we got in design and viewport is smaller component looks like below,

![Image](https://user-images.githubusercontent.com/48857912/188930060-2fae535d-5885-4cf6-8e13-8435a37d14b1.png)

do we expect component to look like this? or is below image is better?

![Image](https://user-images.githubusercontent.com/48857912/188930283-93a3fb53-8939-4590-9864-eeaed4f70424.png)

in both scenerios when action button changes it's location it looks like this. Which seems okay.

![Image](https://user-images.githubusercontent.com/48857912/188930510-4342e713-0a0e-4c7e-ab9f-75ad15322499.png)

How would you suggest us to progress?

**Comment by buseselvi** [comment]
Hi @koulgar , in long description texts we want the button to be centered as below 🙏🏻

<img width="830" alt="image" src="https://user-images.githubusercontent.com/106681486/189095747-c92c65cc-8265-4edb-9018-c9425f0f764d.png">
