### ISSUE TITLE
Textarea Component

### ISSUE THREAD

**Issue by muratcorlu** [Trendyol/baklava#145]
## Design

[Figma Design Document](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?node-id=2641%3A11444)
## Implementation

General usage example:

```html 
<bl-textarea value="Example"></bl-textarea>
```

### Rules

Put some rules about how this component should behave and implemented

* Component will have a default width but can be set by the developer (as in input component)
* By default textarea can be resized by user vertically (Using default behavior of native textarea input)
* Visible row count can be set by the developer (with a default value, 4)
* Optionally, textarea can expand by entering text. In this mode, resizing mode will be disabled. A max row count value can be set by the developer (with a default value)
* Visually, textarea should give the feel that it's in scrollable mode (by showing some part of the text above or below)
* Label styles will be same as the Input component
* Helper and error text, placeholder styles functionality will be provided as in input
* Textarea can have minlength, maxlength validation rules
* Optionally, an active character count can be visible
* If textarea maxlength is provided, this value will be visible inside character count (as like 10 / 100)
* Active character count can exceed the maxlength, but in this case textarea will be in invalid state. And if character counter is visible, this issue will be highlighted in active char count.
* Minlength validation will be visible on character count once user finished entering text (with losing focus for the first time, as in input component)

### `bl-textarea` component

Textarea component is the component to take multi-line text input from user.

#### Attributes

| Attribute | Description | Default Value |
| --------------- | --------------- | --------------- |
| value (`string`) | Value of textarea | - |
| name (`string`) | Name attribute to use textarea inside forms |  - |
| required (`boolean`) | Sets required property of textarea |  - |
| size (`string`) | Sets input size |  medium |
| rows (`number`) | Row count of textarea | 4 |
| expand (`boolean`) | Expands by entering text | false |
| max-row (`number`) | Maximum row count when text area expands | - |
| placeholder (`string`) | Sets the placeholder of textarea | - | 
| label (`string`) | Sets the label of textarea | - | 
| label-fixed (`boolean`) | Makes label as fixed positioned | false | 
| minlength (`number`) | Minimum length of the textarea | - | 
| maxlength (`number`) | Maximum length of the textarea | - | 
| invalid-text (`string`) | Custom error message | - | 
| help-text (`string`) | Helper text of textarea | - | 
| character-count (`boolean`) | Sets visibility of character count | false | 

#### Events

| Event | Description |
| --------------- | --------------- |
| `bl-change` | Fires when an alteration to the element's value is committed by the user. Unlike the bl-input event, the change event is not necessarily fired for each alteration to an element's value. |
| `bl-input` | Fires when the value of an textarea element has been changed. |
| `bl-focus` | Fires when user focuse to textarea.  |
| `bl-valid` | Fires when the value of an input element has been changed. |
| `bl-invalid` | Fires when the value of an input element has been changed. |

**Comment by muratcorlu** [comment]
# Textarea Component Design Meeting Report

Date: 02.11.2022 16:30 (UTC+3)

* Component will have a default width but can be set by developer (as in `input` component)
* By default textarea can resized by used vertically (Using default behavious of native textarea input)
* Visible row count can be set by developer (with a default value, 4)
* Optionally textarea can expand by entering text. In this mode resizing mode will be disabled. A max row count value can be set by developer (with a default value)
* Visually textarea should give the feel that it's in scrollable mode (by showing some part of the text above or below)
* Label styles will be same as Input component
* Helper and error text, placeholder styles functionality will be provided as in input
* Textarea can have `minlength`, `maxlength` validation rules
* Optionally an active character count can be visible
* If textarea maxlength is provided this value will be visible inside character count (as like `10 / 100`)
* Active character count can exceed the maxlength, but in this case textarea will be in invalid state. And if character counter is visible, this issue will be highlighted in active char count.
* Minlength validation will be visible on character count once user finished entering text (with loosing focus for the first time, as in input component)

**Comment by ozkersemih** [comment]
Thanks for feedback @muratcorlu . I just have added new details accordingly what you advise. Can you check again?

**Comment by ozkersemih** [comment]
I added it. Thanks.

**Comment by muratcorlu** [comment]
@ozkersemih I know we decided to use both default slot and `value` attribute to set value, but after [seeing the implementation](#347) and checking out some other libraries, now I think there is no value of having default slot for setting value. It adds extra complication to the implementation as well as usage. We always expect a raw text for the value but slot can have arbitrary content and expectation could be very divers from the users about what will be the value if content has unascaped HTML chars, some components or extra spaces, new lines etc.

So I suggest omitting the default slot and just using `value` attribute to get/set value of the textarea. What do you think?
