### ISSUE TITLE
For outline button type content color of button not set on hover

### ISSUE THREAD

**Issue by mehmetranas** [Trendyol/baklava#194]
**Describe the bug**
When I hover on an outline button, the button text gets invisible. 

**Expected behavior**
For the outline button, the CSS variable `--bl-button-main-hover-color` should be set to the correct color while the user hovers on the button.

**Screenshots**
<img width="774" alt="Screen Shot 2022-08-09 at 16 20 31" src="https://user-images.githubusercontent.com/22976771/183657207-754922aa-34e4-44b3-8963-94df630adc32.png">

**Comment by muratcorlu** [comment]
This is fixed in #187
