### ISSUE TITLE
Triggering release issue in semantic-release

### ISSUE THREAD

**Issue by leventozen** [Trendyol/baklava#199]
In this [pr](https://github.com/Trendyol/baklava/pull/191), it should create new release according to semantic-release [documentation](https://github.com/semantic-release/semantic-release#commit-message-format). However, it didn't. We have `!` and `breaking change message`, that should be considered to fix this issue.

**Comment by muratcorlu** [comment]
We are already in a beta channel of a major release(v2.0). Any breaking change in next branch until we have a stable release of v2 will not trigger another major release. If this was the issue ☺️

**Comment by leventozen** [comment]
Actually the case is semantic-release didn’t release anything after our commit (with ! and breaking change message), so I created this issue but I didn’t have time to look at it yet. However, thanks for your comment @muratcorlu 🚀tomorrow I will define the issue more detailed.
