### ISSUE TITLE
Managing the reset CSS

### ISSUE THREAD

**Issue by DamlaDemir** [Trendyol/baklava#205]
When we use HTML tag it comes with default `user agent styles`. But this causes design problems according to our design system and we have to reset user agent styles in projects.
Maybe we can provide `reset.css` file to reset user agent styles. We should decide to whether add it to the baklava project. 

There is an example for the `p` tag and `ul` tag. We don't want to see these paddings according to our typography Figma design.

<img width="1121" alt="Screen Shot 2022-08-23 at 12 11 37" src="https://user-images.githubusercontent.com/26359615/186120264-cb0e954e-8331-4d1e-a9ce-87cfbb8a26a8.png">

**Comment by muratcorlu** [comment]
This can be tracked in #390
