### ISSUE TITLE
Rubik font-family exceeds design line-height values

### ISSUE THREAD

**Issue by koulgar** [Trendyol/baklava#226]
Title is pretty much self explanatory, rubik font-family that we're currently using exceeds design line-height values.

Line height values should be adjusted accordingly.

**Comment by batuhantozun** [comment]
@buseselvi i just assigned you. can you please check line heights that is @koulgar mentioned?

**Comment by muratcorlu** [comment]
I think this issue is not valid anymore after setting line heights in #354 

Can you confirm? @koulgar @buseselvi
