### ISSUE TITLE
Baklava cannot be used in a create-react-app

### ISSUE THREAD

**Issue by olkeoguz** [Trendyol/baklava#233]
Using Baklava in a CRA fails the whole application

1. Just create a react app by running npx-create-react-app baklavareact
2. npm i @trendyol/baklava
3. Include Baklava library from CDN to your project's
4. Import BlButton in app.tsx
5. npm start 

![Screen Shot 2022-09-12 at 11 11 23](https://user-images.githubusercontent.com/70342517/189605053-14979d4b-64fa-4e45-8f0f-d10798efc507.png)

**Comment by muratcorlu** [comment]
As far as I see you import `BlButton` from `baklava.js`. Instead you need to import it from `baklava-react.js`. Like

```ts
import { BlButton } from "@trendyol/baklava/dist/baklava-react";
```

If this is the reason we may consider improving [our React document](https://trendyol.github.io/baklava/?path=/docs/frameworks-react--page).

If that's not the reason, it would be great if you can reproduce this in a public place that we can debug.
