### ISSUE TITLE
Documentation - Specifying version number for all CDN imports

### ISSUE THREAD

**Issue by leventozen** [Trendyol/baklava#244]
In this issue, I will fix the version number inside `package.json` and generate `CHANGELOG.md` inside the project folder to increase change log visibility. Also, I will replace version numbers inside `Vue` and `React` stories and `README.md`.
For stories, the `package.json` fix would be enough, because it can read the version number from `package.json`.
For README.md, we should replace the version number inside it before every release and commit it automatically.

Any suggestions? @muratcorlu

**Comment by leventozen** [comment]
Considering deploying storybook after release with the release tag and using this tag, we may have a chance to update the version number inside stories.

**Comment by leventozen** [comment]
UPDATE: I opened this issue to make our CDN URLs up to date. We had some drawbacks about simply purging the [url](https://github.com/Trendyol/baklava/discussions/180). Dimitry from jsDelivr sent me an email about it. They have plans to add authorization for purging. Right now, they have rate limits for API calls to prevent abuse. So, I am going to add a new action to purge after every release. Still kinda abusable, but we can wait for authorization.

**Comment by muratcorlu** [comment]
Mentioning versions in the installation guides will be needed anyway when we have multiple major versions. But for now I think it's ok to continue with that. Maybe #258 can open new doors about this.

I think we can close this issue for now and maybe create separate issue for purging jsdelivr caches on releases.

**Comment by leventozen** [comment]
+1 I agree to separate the issue with purging jsdelivr caches on releases. I am closing this issue .
