### ISSUE TITLE
Tooltip overflow problems

### ISSUE THREAD

**Issue by Enes5519** [Trendyol/baklava#247]
**Describe the bug**
It doesn't work correctly on overflow patterns.

**To Reproduce**
1. Create overflow table
2. Add tooltip

**Expected behavior**
See all tooltip content.

**Screenshots**
![image](https://user-images.githubusercontent.com/10272532/191737545-2adf1fb0-4f65-4acc-9d24-43edf3e70d05.png)
![image (2)](https://user-images.githubusercontent.com/10272532/191737504-7bd46117-ef7b-43f4-811f-7eaa2412ce99.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.4
 - Browser: Firefox
 - Version: 104.0.2

**Comment by muratcorlu** [comment]
Tooltip component uses fixed positioning, so it should not have a problem with overflowing parent. Can you reproduce this in a public environment? I tried with a codepen here and it looks ok: https://codepen.io/muratcorlu/pen/XWqaONd

**Comment by Enes5519** [comment]
Sure 👍 . [Stackblitz](https://stackblitz.com/edit/vitejs-vite-mqmpeb?file=src/App.jsx)

**Comment by muratcorlu** [comment]
Stackblitz didn't work on my Firefox and Safari. I dowloaded the project and checked it on Chrome, Firefox and Safari and couldn't notice any issue. I tried with Firefox 105.

For clarity: Does it happen only on Firefox for you? Or does it also the case on Chrome or Safari?

**Comment by Enes5519** [comment]
No problem in Chrome. Firefox (104.0.2) and Safari (15.5) has problem.

**Comment by Enes5519** [comment]
You need to trigger the sticky element. To do this, you need to reduce the viewport width.

**Comment by Enes5519** [comment]
I wrote new code for the triggered version. Overflow and sticky effects. I mentioned it in the comment lines. [Codepen](https://codepen.io/enes5519/pen/XWqVRGb)
