### ISSUE TITLE
bl-button type="submit" not working

### ISSUE THREAD

**Issue by AykutSarac** [Trendyol/baklava#259]
**Describe the bug**
`<bl-button type="submit">` is not working as intended.

**To Reproduce**
1. Put bl-button inside form element
2. Set button type to "submit"
3. Submit form
4. Not working, however it does work with normal button

**Expected behavior**
Should validate input elements

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: MacOS
 - Browser [e.g. chrome, safari]: Brave

**Additional context**

**Comment by muratcorlu** [comment]
Hello. Thanks for reporting. This is a known limitation for now and planned to fix. We already have an issue here #251 You can track with it.

I'll close this now for tracking on #251
