### ISSUE TITLE
Split Button Component

### ISSUE THREAD

**Issue by leventozen** [Trendyol/baklava#264]
[Figma](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?node-id=2161%3A9122)

**Comment by muratcorlu** [comment]
## Split Button Component Design Meeting Report

Date: 05.10.2022 15:30 (UTC+3)

* Split Button component is very similar to Dropdown Component with a key difference: Split Button is a Dropdown that one action is put forward as the main action.
* Split Button will be always a **primary** button.
* Split Button main action button can optionally have an icon.
* It'll have 3 size variants as button component has.
* Same rules will apply for the popover part of the Dropdown component.
