### ISSUE TITLE
Input type number doesn't accept value as its type and return

### ISSUE THREAD

**Issue by AykutSarac** [Trendyol/baklava#298]
**Describe the bug**
Input with type of **number** doesn't accept value as its type and only accepts string, it creates odd work for conversion from string to number and vice versa

**Expected behavior**
Should accept string and number as value and return number in case of input type given as number

**Versions**
Baklava v2.0.0-beta.38
React 18.2.0

**Comment by AykutSarac** [comment]
`onChange` doesn't work on Input fyi

**Comment by muratcorlu** [comment]
> `onChange` doesn't work on Input fyi
> 
> EDIT: apparently it fires when input gets blurred, so it works unlike the generic input?

Generic input also fires `change` event when it's blurred. 

> Unlike the [input](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event) event, the change event is not necessarily fired for each alteration to an element's value.
> https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event

**Comment by muratcorlu** [comment]
You need to use `onInput` for tracking changes on every keydown.
