### ISSUE TITLE
Select `selectedOptions` not working

### ISSUE THREAD

**Issue by AykutSarac** [Trendyol/baklava#303]
**Describe the bug**
Select component's `selectedOptions` attribute not working

**To Reproduce**
1. Create Select component & create SelectOptions
2. Set selectedOptions

**Example**
```js
<BlSelect selectedOptions={[{ text: "a", value: "a", selected: true }]}>
    <BlSelectOption value="a">aaaa</BlSelectOption>
    <BlSelectOption value="b">bbbb</BlSelectOption>
</BlSelect>
```

**Versions**
Baklava v2.0.0-beta.39
React 18.2.0

**Comment by mustafafrw** [comment]
Hello Aykut,

`selectedOptions` attribute is not defined in the `bl-select` component, it is only a getter. You can set `selected` attribute to each `bl-select-option` to show them in selected state. But I think such a use (set all of them via parent) should also be considered.

**Comment by AykutSarac** [comment]
> Hello Aykut,
> 
> `selectedOptions` attribute is not defined in the `bl-select` component, it is only a getter. You can set `selected` attribute to each `bl-select-option` to show them in selected state. But I think such a use (set all of them via parent) should also be considered.

Hi, thank you for clarification. I think managing selected options from parent would be so handy.
