### ISSUE TITLE
Define z-index values

### ISSUE THREAD

**Issue by olkeoguz** [Trendyol/baklava#305]
[Figma](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?node-id=2630%3A11329)

### Discussed in https://github.com/Trendyol/baklava/discussions/276

<div type='discussions-op-text'>

<sup>Originally posted by **DamlaDemir** October  3, 2022</sup>
**Describe the bug**
The select component doesn't appear correctly.

**To Reproduce**
1. Go to https://6267ebb4dd54f5004a65f14a-xabmjaqqco.chromatic.com/?path=/docs/components-pagination--basic-usage
2. Go to select section.
3. Click show code.
4. Click select.

**Screenshots**
![image](https://user-images.githubusercontent.com/26359615/193558830-1d77bd84-bba0-4569-9523-65581854f6f6.png)

**Solution**
To fix this problem, we should increase the popover's z-index value in select. Z-index is a common problem. We should set as correctly all of our components' z-index values. We can research the best practices on this topic.
</div>

**Comment by muratcorlu** [comment]
Some z-index levels are defined in our [figma document](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?node-id=2630%3A11329&t=2lcnN74cwYVe8UbQ-0). Some numeric values should be defined in our design tokens and all of the z-index definitions in component styles should be updated accordingly.

**Comment by AykutSarac** [comment]
Input icon is on top of the select option, fyi.

<img width="425" alt="image" src="https://user-images.githubusercontent.com/47941171/214860221-79624b2d-21a8-4193-bed7-fdf81233b682.png">

**Comment by muratcorlu** [comment]
Nice catch @AykutSarac! It will be fixed in #389 I removed z-index from the icon in that PR. But that's a nice example about the effect of not having a start about z-indexes 😊
