### ISSUE TITLE
Tooltip component is not responsive

### ISSUE THREAD

**Issue by mahmudmardini** [Trendyol/baklava#310]
The current tooltip width is not responsive on the small screens.

<img width="513" alt="Screen Shot 2022-11-03 at 07 54 00" src="https://user-images.githubusercontent.com/38536438/199651144-0c8c6d26-2ac3-4df2-a9ec-8a675962b95c.png">

**Comment by DamlaDemir** [comment]
While developing the tooltip, we did not develop it as responsive. We should fix it in accordance with the responsive design.
Can we work on this @buseselvi ?

**Comment by buseselvi** [comment]
we should work on mobile view 👌🏻 @DamlaDemir
