### ISSUE TITLE
Tooltip is keep showing at the same position of screen when we scroll in touchable screens

### ISSUE THREAD

**Issue by mahmudmardini** [Trendyol/baklava#311]
In touchable screens like iPad, tablets, and phones when we open a tooltip and scroll down or up, the tooltip keep appearing in the wrong position.
Check the video below for more information.

https://user-images.githubusercontent.com/38536438/199652516-99e380e9-c603-4837-90a6-894042a7cb0f.mp4

**Comment by DamlaDemir** [comment]
We know this problem, but unfortunately, we could not find a solution for it for now. This happens because we have given the tooltip position as `fixed`.
If we do not give `fixed`, the tooltip does not work correctly. Maybe we can do a little more research on it. Any ideas would be of great help.

**Comment by muratcorlu** [comment]
I'm working on this by implementing the solution that we used in `select` component. https://floating-ui.com/docs/autoUpdate
