### ISSUE TITLE
Unclickable  links in tooltip

### ISSUE THREAD

**Issue by mahmudmardini** [Trendyol/baklava#312]
If there is a link in the tooltip text, it's can not be clicked because the mouseover event is firing only for the button, not for the tooltip box.
For more details check the video below.

https://user-images.githubusercontent.com/38536438/199654158-11b6a4fe-3859-4516-b103-74ffb6adbc83.mp4

**Comment by DamlaDemir** [comment]
Hi, thank you for the issue @mahmudmardini 

We talked about this when we developed the tooltip. We decided there will be no clicks in the tooltip for Phase 1 with the design team. Do you have any clickable tooltips in your projects?
If you have maybe we can evaluate it for Phase 2. What do you think @buseselvi ?

**Comment by mahmudmardini** [comment]
Hi @DamlaDemir, yes we have some clickable text in our tooltips. 
It would be great if this feature could be added. thanks for your response.

**Comment by muratcorlu** [comment]
Is it an idea to add some delay (like 500ms) before hiding tooltip and cancel hiding if user hover over tooltip during that time? Otherwise we'll need to trigger tooltip by click instead of hover (as we already do on touch screens). What do you think? @buseselvi

**Comment by buseselvi** [comment]
Can we make it appear on the hover and stay open when clicked? @muratcorlu

**Comment by muratcorlu** [comment]
@buseselvi Yes we can but do you think users can notice this difference?

**Comment by buseselvi** [comment]
@muratcorlu To clarify the difference between the two uses, we can divide them into hover and click tooltip. If there is no clickable action, it will appear on the hover, if there is, it will be opened with a click. Since we mostly use it with the button component, users can understand that it is clickable from the hover states.

**Comment by muratcorlu** [comment]
Regarding to [A11Y guides](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tooltip_Role), tooltip should appear with hover or focus on owning element. And they suggest to not focus content inside tooltip:

> The tooltip never receives focus. Focus stays on the owning element.
>
> https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tooltip_Role#required_javascript_features

I'm not sure if putting a link inside a tooltip is a good idea. Maybe we should avoid this and keep tooltip contents as basic text always. If we really need to show more complicated things, we may use a popover component instead.

**Comment by buseselvi** [comment]
As the design team, we examined the designs with the link in the tooltip and solved it by not using the tooltip for them. We decided not to give any links or buttons in the tooltip. 🚀

**Comment by muratcorlu** [comment]
So then, @mahmudmardini can you check with your designer about the design solution here? Is it ok for you to close this issue with that resolution?

**Comment by mahmudmardini** [comment]
Yes, we discussed this issue, and we can close it.
Thank you
