### ISSUE TITLE
The select component does not update when one of the select options is selected programmatically

### ISSUE THREAD

**Issue by umitkucuk** [Trendyol/baklava#317]
**Describe the bug**
When I change the selected options by state, the select component itself does not update.

**To Reproduce**
1. Decide which option should be selected with a state
2. Change the state from somewhere else
3. The select component does not get an update

**Expected behavior**
When I select the options programmatically (via the state), the select component itself should get an update according to the state changes.

**Screenshots**
https://codesandbox.io/s/react-typescript-forked-0fh8qn?file=/src/App.tsx

**Comment by muratcorlu** [comment]
This should be fixed with #287
