### ISSUE TITLE
Alert Component Adjustments

### ISSUE THREAD

**Issue by batuhantozun** [Trendyol/baklava#318]
With #141 (Notification Component) we need to improve Alert Component.
Details will be here when design is done.

**Comment by buseselvi** [comment]
We updated the Alert Component design and documentation: [Figma](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?node-id=2815%3A14630&t=LTV8aIHmM6Yu2Q0k-1)
