### ISSUE TITLE
Bubbling and propagation problem in nested dialog

### ISSUE THREAD

**Issue by DamlaDemir** [Trendyol/baklava#342]
**Describe the bug**
When using nested dialog in the Vue 2 project, we noticed that every dialog closes when we click the close button of the child dialog or press the esc key.

**To Reproduce**
1. Go to https://codesandbox.io/s/vue-2-playground-forked-wrxmzy?file=/src/App.vue
2. Click on open parent dialog button
3. Click on open child dialog button
4. Click on close button
5. You will see the every dialog is closed

**Expected behavior**
When we click the close button of child dialog or esc key we should only see it close.

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser Chrome

**Additional context**
This problem probably occur because of bubbling and propagation. When I add the stop (it is equal event.stopPropagation()) like this:

```html
<bl-dialog
 :open="openChildDialog"
 @bl-dialog-close.stop="openChildDialog = false">
   Child Dialog
</bl-dialog>
```

The `stop` fixes the close button problem but esc problem is going on.

**Comment by muratcorlu** [comment]
@DamlaDemir Codesandbox link shows a pagination example now. Did you change it, or wrong link?

**Comment by DamlaDemir** [comment]
Sorry, i added wrong link. I fixed 👍
