### ISSUE TITLE
Notification Component

### ISSUE THREAD

**Issue by onursert** [Trendyol/baklava#349]
## Design

[Figma Design Document
](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?node-id=80%3A3131&t=mOa06L4RJiSCbIvJ-0)

## Implementation

General usage example:

```html 
<bl-notification
    variant="info"
    caption="Info Caption"
    description="Info Description"
    permanent
    swipe
>
    Info Notification Component Text
</bl-notification>
```

### Rules

Put some rules about how this component should behave and implemented

* `permanent` attribute controls the component visibility. If true component stays on the screen, if false component disappears after 7 seconds. (For default it's false.) (If a user hover their mouse over component, countdown stops.)
* `swipe` attribute controls the component dismiss functionality. If true component can be dismissed by swipe to right. (For default it's false.)

### `bl-notification` component

Notification component displays an informational message to users for a while with additional features if desired.

Description

#### Attributes

| Attribute | Description | Default Value |
| --------------- | --------------- | --------------- |
| variant (`string`) | Decides variants of notification box ( `info`, `success`, `warning`, `error` )  | `"info"` |
| caption (`string`) | Sets notification caption  | - |
| description (`string`) | Sets notification description  | - |
| permanent (`boolean`) | Stays component always on the screen  | `false` |
| swipe (`boolean`) | Makes component swipeable to dismiss  | `false` |

**Comment by muratcorlu** [comment]
Issue will be handled in #141. Closing this.
