### ISSUE TITLE
No background color checkmark of checkbox component

### ISSUE THREAD

**Issue by yasin749** [Trendyol/baklava#353]
**Describe the bug**
Checkmark of checkbox component doesn't have background color. Checkmark takes the background color of the container it is in.

**Expected behavior**
Checkmark may be default white background and takes other colors via style props.

**Screenshots**
![Screen Shot 2023-01-04 at 14 40 23](https://user-images.githubusercontent.com/6948992/210552581-e923f726-50bd-41cc-af60-206773450fff.png)

**Comment by muratcorlu** [comment]
Good catch. We need to add a UI test for ensuring this. Any PRs are very welcome for the fix.
