### ISSUE TITLE
Add suffix and prefix to input

### ISSUE THREAD

**Issue by Enes5519** [Trendyol/baklava#388]
![IMG_3549](https://user-images.githubusercontent.com/10272532/214511626-423e2a50-20b5-4f76-a281-ccf6a28d0cc5.jpg)

**Comment by muratcorlu** [comment]
This feature is added to our plan last monday and design team is already working on it. You can track process with it's issue: #391 (Sorry that I converted this draft issue to real one, just a few minutes ago)
