### ISSUE TITLE
Masking Capability for Input Component

### ISSUE THREAD

**Issue by muratcorlu** [Trendyol/baklava#391]
Leading and trailing texts (like currencies or units) would be possible to put our Input component. Details will come later.

**Comment by muratcorlu** [comment]
Design changes are ready: https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?node-id=4%3A5586&t=dpos9bPGKoCkqo5m-0

**Comment by doganozturk** [comment]
This task had originally title **Leading/Trailing text for Input field**.

We talked about this and decided to implement this feature with usage of input's placeholder functionality and usage of input masking.

**Comment by doganozturk** [comment]
Our latest decision is not to implement input masking as a feature but provide detailed examples with compatible libraries. **Leading/Trailing text for Input field** should be achieved by placeholder usage and input masking integration with 3rd party libraries such as IMask and Maskito.
