### ISSUE TITLE
React prop labelFixed is not converted into attribute

### ISSUE THREAD

**Issue by AykutSarac** [Trendyol/baklava#392]
**Describe the bug**
When used labelFixed as component property, it doesn't serve it as label-fixed and being ignored on production.

**Expected behavior**
Convert labelFixed to label-fixed when build.

**Screenshots**
<img width="389" alt="image" src="https://user-images.githubusercontent.com/47941171/214781848-ecfa0718-4fed-40cb-94f6-d97a9092ca78.png">

<img width="341" alt="image" src="https://user-images.githubusercontent.com/47941171/214781880-0189c096-26e0-4283-aba6-17ddfb226775.png">

**Comment by muratcorlu** [comment]
#379 should have fixed this issue. Can you confirm you use the version beta.61 or above?
