### ISSUE TITLE
Baklava identifies itself as Unknown in React

### ISSUE THREAD

**Issue by Enes5519** [Trendyol/baklava#397]
**Describe the bug**
Baklava not work in React 16. It identifies itself as "Unknown" component.
Possible: React Lazy Exports

**To Reproduce**
1. Upgrade baklava version to 2.0.0-beta.59 from 2.0.0-beta.48

**Screenshots**
<img width="365" alt="Screen Shot 2023-02-02 at 11 01 12" src="https://user-images.githubusercontent.com/10272532/216265786-c91111d4-2736-46ed-9081-eab1c1a8255c.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser [e.g. chrome, safari]: Firefox
 - Version [e.g. 22]: 59

**Comment by olkeoguz** [comment]
@muratcorlu With the release of lazily loading baklava components (https://github.com/Trendyol/baklava/pull/320), we were expecting baklava not to work in React 16 and some versions of 17 since they handle React Lazy differently.  We don't have any issues with the 18 though.

**Comment by muratcorlu** [comment]
I'm trying to debug this. I created a demo with React 16 and TS and apparently managed to run Baklava (beta75) in it without any issues. @Enes5519 can you check this: https://codesandbox.io/s/baklava-in-react-16-ts-ninfd0?file=/src/index.tsx

I feel there is a problem about either TS version or tsconfig.

**Comment by muratcorlu** [comment]
Can you check if #449 fixes the issue here?
