### ISSUE TITLE
Strange padding at Textarea

### ISSUE THREAD

**Issue by AykutSarac** [Trendyol/baklava#400]
**Describe the bug**
There is a strange padding at the top of Textarea that other components typically doesn't have. This ruins the styling when used in a form.

**Expected behavior**
No padding

**Screenshots**
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/47941171/217168008-0d419b57-2f98-4fe6-961c-2b220f2507b8.png">

**Additional context**
Baklava.2.0.0-beta.65

**Comment by muratcorlu** [comment]
I know what is it. It was also there in Input component but I removed it lately in #389. But textarea started before that fix and included same padding as well.

I'll fix this today.
