### ISSUE TITLE
Alignment with error message

### ISSUE THREAD

**Issue by AykutSarac** [Trendyol/baklava#426]
**Describe the bug**
I want to align the button and input next to each other, label-fixed enabled. However when the error message is shown the alignment is getting broken.

**Expected behavior**
Alignment should be kept nonetheless. 

**Screenshots**
https://user-images.githubusercontent.com/47941171/219015156-4637cadf-420e-4eb8-b055-3f8fecf9f94f.mov

 - Version 71

**Comment by AykutSarac** [comment]
It also has a weird behaviour with BlSelect and BlInput when wrapped with display flex and align baseline.
BlSelect
<img width="800" alt="image" src="https://user-images.githubusercontent.com/47941171/219015899-f96fbc0d-af90-46dd-a6f9-4c777cf07ca8.png">

BlInput
<img width="788" alt="image" src="https://user-images.githubusercontent.com/47941171/219015985-2cf147b6-4c53-4b28-9b48-bb354d8e9a44.png">

**Comment by muratcorlu** [comment]
I'm working on #287 and this will be fixed there as well. (I already fixed it in my branch).

**Comment by muratcorlu** [comment]
But, good to be aware: When error message showed, height of the select component will be bigger since we don't reserve extra empty space below for messages (same in input). So if you align select with something next to it with vertical centering, error text will break it. To avoid this, you may consider adding a `help-text` which will contain some information below field when there is no error.

**Comment by muratcorlu** [comment]
I just noticed that positioning a button next to a form field with a fixed label (`label-fixed`) can be also a challenge. For that kind of cases you can define a rule like below in your CSS:

```css
[label-fixed] ~ bl-button {
  margin-top: calc(var(--bl-size-3xs) + var(--bl-font-caption-line-height));
}
```

This will add exact same space of the height of the label of a medium sized input to the bl-button next to a fixed-labeled field. Example:

<img width="318" alt="image" src="https://user-images.githubusercontent.com/127687/220212645-e5ffe4eb-b07c-4c2d-9dff-096a25e5892d.png">
