### ISSUE TITLE
Baklava input, select etc. element problem. Not working BS modal

### ISSUE THREAD

**Issue by erdemerciyas** [Trendyol/baklava#428]
![image](https://user-images.githubusercontent.com/23054721/219341262-31c5d4a1-59af-43be-9906-f7878b5de1f1.png)

Baklava Select component works wrong on BS modal.
We need full size input element. (width:100%) Sizes are restricted. Not working full width

**Comment by muratcorlu** [comment]
> We need full size input element. (width:100%) Sizes are restricted. Not working full width

Ah I just noticed there are 2 problems reported here. What is the issue about input width here? Can you give an example? @erdemerciyas

**Comment by erdemerciyas** [comment]
@muratcorlu 
![image](https://user-images.githubusercontent.com/23054721/219388484-294b95b7-1c6d-44d1-832f-622a23a19a59.png)

We need responsive input element. Current elements work with fixed width

**Comment by muratcorlu** [comment]
@erdemerciyas Input and select has default width but you can change them for your needs. I made an example: https://codepen.io/muratcorlu/pen/xxabNMN

Please check and confirm if something like this is a good solution for you.

**Comment by erdemerciyas** [comment]
@muratcorlu full width work perfect. Thank you. We are waiting select elelment dropdown position ...

**Comment by muratcorlu** [comment]
@erdemerciyas I couldn't reproduce the issue in dialog. Here an example bl-select select in an bl-dialog, and works fine. https://codepen.io/muratcorlu/pen/vYzOezY

<img width="518" alt="image" src="https://user-images.githubusercontent.com/127687/219603717-707910ba-ad90-486e-8dd8-31788322a653.png">

Can you reproduce the issue in a playground?

**Comment by erdemerciyas** [comment]
@muratcorlu Select working perfect with Baklava modal. The same problem persists in our system.

Exp. https://codepen.io/erdem-erciyas/pen/poOJdxY

**Comment by muratcorlu** [comment]
Using `transform: translate()` in CSS changes the logic for fixed positioning. That causes this issue. I'll consider adding an option to use `absolute` positioning for select.

In the meantime, I would suggest to use Baklava Dialog since it uses native HTML Dialog element and has many advantages about a11y and consistency with other baklava components.

**Comment by erdemerciyas** [comment]
@muratcorlu  I will talk to our teammates and give information about Baklava modal. Thank you very much

**Comment by erdemerciyas** [comment]
@muratcorlu  i solved problem. Changed BS Modal (transform - translate)

![image](https://user-images.githubusercontent.com/23054721/219624925-b24b99e7-9594-4c48-8639-115163d3e54d.png)

**Comment by erdemerciyas** [comment]
![image](https://user-images.githubusercontent.com/23054721/219625715-c6a8c8a3-7b27-4f01-9f0a-08f3451027c5.png)

Thank you very much. Best regards

**Comment by muratcorlu** [comment]
It's good you managed to fix it.

We'll also add a CSS variable to customize popover positioning soon. It may help for people who have to use `transform: translate`. I'll update here once it's added.
