### ISSUE TITLE
bl-icon clock icon 404 not found

### ISSUE THREAD

**Issue by fatihhayri** [Trendyol/baklava#440]
<bl-icon name="clock" title="clock"></bl-icon>

bl-icon clock not found error

https://codepen.io/fatihhayri/pen/eYLzpqK

**Comment by fatihhayri** [comment]
bl-icon clock not found error

**Comment by muratcorlu** [comment]
`clock` icon was named as `waiting` and renamed in #432 as current name and released with beta.74. In the example you use beta.41. I suggest to use latest version, otherwise you can use it as `waiting`.

**Comment by fatihhayri** [comment]
Thank you!
