### ISSUE TITLE
Add support for pattern to Input component

### ISSUE THREAD

**Issue by AykutSarac** [Trendyol/baklava#452]
**Is your feature request related to a problem? Please describe.**
[Pattern](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern) is a widely used attribute to validate user inputs

**Describe the solution you'd like**
Add validation support for pattern attribute to input

**Comment by muratcorlu** [comment]
Let's fix this together with some other missing attributes in #405 as well. Please subscribe to that issue for updates.

And you know, any PRs are very welcome. 😊
