### ISSUE TITLE
Dialog actions should be full width

### ISSUE THREAD

**Issue by mustafafrw** [Trendyol/baklava#461]
**Is your feature request related to a problem? Please describe.**
Currently, dialog actions are located at the bottom right of the dialog. However, in some designs, it can  be necessary to use the entire area. You can look at the screenshot as an example.

**Describe the solution you'd like**
If the dialog takes a property like `blockActions` or something, then the childs in the footer area can be assigned the flex: 1 css property.

**Additional context**
![image](https://user-images.githubusercontent.com/49120729/222438094-2138a2e3-5a75-4e16-b5cd-b339fe692666.png)

@buseselvi

**Comment by buseselvi** [comment]
For center-aligned dialog contents, it may be necessary to use the button's block property. @muratcorlu can we add this as an option, what do you think?

**Comment by muratcorlu** [comment]
Apparently this also works well with our responsive mode.

<img width="678" alt="image" src="https://user-images.githubusercontent.com/127687/222542412-0ffb28cf-01c0-4064-b114-00e5c3051357.png">

If this will be accepted as a valid use case maybe we should consider mentioning this option in our documentation too.

**Comment by buseselvi** [comment]
@muratcorlu perfect! we should definitely mention this in the storybook, we thought we couldn't do it  🥲
