### ISSUE TITLE
Input field doesn't update programmatically

### ISSUE THREAD

**Issue by AykutSarac** [Trendyol/baklava#468]
**Describe the bug**
When input is set programmatically it doesn't get updated internally and form doesn't validate values.

Baklava 2.0.0-beta.78

**Comment by AykutSarac** [comment]
This could be effecting variants such as Textarea and other components.

**Comment by muratcorlu** [comment]
This should be fixed with #460. Can you confirm? @AykutSarac

**Comment by AykutSarac** [comment]
It's fixed, thank you!
