### ISSUE TITLE
'Select All' for Select Component

### ISSUE THREAD

**Issue by muratcorlu** [Trendyol/baklava#520]

**Comment by muratcorlu** [comment]
## Design Meeting Report

Date: 2023-04-18 14:00 GMT+3

---

* "Select All" functionality will be visible by default in multi-select mode
* "Select All" will be sticky on popover. Will not disappear with scroll
* Popover height will still include up to 6 items even if "select all" visible. That means popover height in multi-select mode will be able to bigger than single select mode.
* To make all of the selected items easily visible, selected items will be moved to the top of the list when popover opened (order will not change immediately, when user select/deselect an item)
* "Select all" checkbox will be "indeterminate" mode if some of the options are un-selected.
* "Select all" will not effect current behaviour on showing selected options inside select input. That means, it will still show like "label 1, label 2, label 3, +21" as in if user selects all of the items one-by-one.

**Comment by buseselvi** [comment]
We are planning to make a prototype test with the ux research team about select all and select search to designs before handing 🙏🏻

**Comment by muratcorlu** [comment]
Our UX Research started on this together with #265. Results will come soon.

**Comment by buseselvi** [comment]
Here is the [design documentation link](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?type=design&node-id=4378%3A23660&t=E8wULDVAUnoZCOwA-1) 🚀

**Comment by ogunb** [comment]
> * To make all of the selected items easily visible, selected items will be moved to the top of the list when popover opened (order will not change immediately, when user select/deselect an item)

This seems beyond the scope of the issue. [I created another one for it.](https://github.com/Trendyol/baklava/issues/744)

**Comment by ogunb** [comment]
## Design
[Figma Design Document](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?type=design&node-id=4378%3A23660&t=E8wULDVAUnoZCOwA-1)

## Implementation
General usage example:

```html
<bl-select 
  multiple 
  placeholder="Choose countries"
  hide-select-all
  select-all-text="Tümünü Seç"
>
  <bl-select-option value="tr">Turkiye</bl-select-option>
  <bl-select-option value="nl">The Netherlands</bl-select-option>
  <bl-select-option value="de">Germany</bl-select-option>
  <bl-select-option value="uk">United Kingdom</bl-select-option>
</bl-select>
```

### Rules

* `hide-select-all` attribute will hide the "select all" option. False by default.
* `select-all-text` attribute will change the text of the "select all" option. This will be removed when localization is implemented.
* "Select all" option is sticky.
* Popover height will still include up to 6 items even if "select all" visible. That means popover height in multi-select mode will be able to bigger than single select mode.
* "Select all" checkbox will be "indeterminate" mode if some of the options are un-selected.
* "Select all" will not effect current behaviour on showing selected options inside select input. That means, it will still show like "label 1, label 2, label 3, +21" as in if user selects all of the items one-by-one.
* "Select all" will not take any action on disabled options.

### API Reference

New attributes:

| Attribute                  | Description                                                             | Default Value |
| -------------------------- | ----------------------------------------------------------------------- | ------------- |
| `hide-select-all`          | Hides the "select all" option.                                          | `false`       |
| `select-all-text`          | Changes the text of the "select all" option.                            | `Select All`  |
