### ISSUE TITLE
I should be able to change off color of the switch component

### ISSUE THREAD

**Issue by ogunb** [Trendyol/baklava#523]
**Is your feature request related to a problem? Please describe.**
In some designs, it's necessary to indicate status using success and danger colors (such as indicating whether a restaurant is open or closed).

**Describe the solution you'd like**
Currently, we have the `--bl-switch-color` CSS property, but we need to add another for the unchecked state.

<img width="468" alt="Screenshot 2023-04-12 at 12 45 20" src="https://user-images.githubusercontent.com/24693913/231420665-0da08804-86c2-4520-9b85-b89b4fb679aa.png">

**Comment by buseselvi** [comment]
Green and red color usage in switch component is very common actually. But in the image open and close states seems kinda wrong to me. Shouldn't it be like this? @muratcorlu @ogunb 

<img width="253" alt="image" src="https://user-images.githubusercontent.com/106681486/231427916-202e71bb-b402-4f70-bda3-10dae2ad94e9.png">

**Comment by ogunb** [comment]
Yes, I screenshotted that from the design, didn't even realize it. 😄 

I'll open a PR for this then.

**Comment by buseselvi** [comment]
Btw we shouldn't be able to set any color except `--bl-color-success` for **switch on** and `--bl-color-danger` for switch off. If a different color is wanted users can set a different color theme for it.

**Comment by muratcorlu** [comment]
Firstly, we can not make a breaking change now. We just released our first major version. So renaming or removing the current variable is not an option for the near future.

Secondly, -as @ogunb mentioned- currently we don't force users to use either success or danger colors. We use primary color by default for "checked" state, and `neutral-lighter` color for the unchecked state. And we allow developers to set change checked color with any color they can. We can add some guidance about picking the best colors for different use cases in our documentation, that would be very helpful, I think.

I would suggest keeping `--bl-switch-color` as is, and adding `--bl-switch-color-off` and `--bl-switch-color-on` with current default values. Then we can use the current `--bl-switch-color` as an alias of `--bl-switch-color-on`, flag it as deprecated in favor of `--bl-switch-color-on` and remove it in v3.

So in technical terms:

```css
--switch-color: var(--bl-switch-color-on, var(--bl-switch-color, var(--bl-color-primary)));
```

**Comment by ogunb** [comment]
In our Figma documentation, the switch component's focus state is showcased with the primary color. The implementation sets the focus color to be the same as `--switch-color`, which means that even if you set the color to green, a green outline will be shown around the switch when it's in focus.

This behavior appears to be acceptable until the off color is changed. Since our buttons change their focus color depending on their own color, should the switch component behave in the same way?

![Screenshot 2023-04-12 at 16 37 15](https://user-images.githubusercontent.com/24693913/231475069-a4a5d038-c8dc-4d08-825a-2997350987cd.png)

![Screenshot 2023-04-12 at 16 38 49](https://user-images.githubusercontent.com/24693913/231475499-aceacc40-b767-48a5-b34e-fea07fb77847.png)

![Screenshot 2023-04-12 at 16 39 14](https://user-images.githubusercontent.com/24693913/231475583-edfee7e3-2ca2-4430-8dcd-761f16a72260.png)

![Screenshot 2023-04-12 at 16 39 06](https://user-images.githubusercontent.com/24693913/231475555-6e022763-1575-418c-8ec7-e6376672a819.png)

**Comment by muratcorlu** [comment]
This leads me another issue I see here. With arbitrary colors, it's not very clear if it's "on" or "off". For example when I see that switch with danger color, by alone, I can not immediately understand if it's "off" or "on". Sometimes openine something can be also dangerous, right? 😊 

I thought there should be something else other than just color that indicate the state of the switch. I noticed iOS has an option like below in accessibility settings:

![IMG_9771](https://user-images.githubusercontent.com/127687/232079802-97a50f15-8575-43fd-9b7f-11de72e2c57e.jpg)

Maybe we can also consider a mode like that for our switch. Of course, this can be a separate improvement.
