### ISSUE TITLE
Using icon component with custom icon sets

### ISSUE THREAD

**Issue by muratcorlu** [Trendyol/baklava#525]
I think it would be nice to allow people to use our icon component with custom, external icon sets. I think [we can inspire from Shoelace](https://shoelace.style/components/icon?id=icon-libraries) for this and give the ability to register custom icon sets by still keeping current icon set by default.

```html
<script type="module">
  import { registerIconLibrary } from '@trendyol/baklava';

  registerIconLibrary('bootstrap', {
    resolver: name => `https://cdn.jsdelivr.net/npm/bootstrap-icons@1.0.0/icons/${name}.svg`
  });
</script>

<bl-icon library="bootstrap" name="arrow-up"></bl-icon>
```

**Comment by ogunb** [comment]
We have decided against implementing this feature for the time being.

Users can change the icon pack by using the `setIconPath` utility, provided they supply all icons with the same names. However, we do not endorse or officially support this method.

We may revisit this feature in the future. If anyone feels the need for this functionality, please feel free to reopen the issue.
