### ISSUE TITLE
Publishing icon library as a separate NPM package

### ISSUE THREAD

**Issue by muratcorlu** [Trendyol/baklava#530]
As a common practice, it would be better to exclude our default icon library as a separate npm package. Since it's also [used in our react-native implementation](https://github.com/Trendyol/baklava-react-native/tree/main/src/icons), that would reduce repetition much.

## Proposal

- [x] We'll create a new repository named `baklava-icons`
- [ ] Package will be automatically published to NPM with `@trendyol/baklava-icons` name.
- [ ] Package will contain raw SVG files
- [ ] Package will contain React Native wrapper components. Those will be auto-generated
- [ ] SVG files would be consumed via jsDelivr
- [ ] React Native Wrappers would be consumed via NPM
- [ ] [Adding icon tutorial](https://baklava.design/?path=/docs/design-system-icons-adding-new-icons--page) would be updated accordingly.
- [ ] Icon documentation would come from `baklava-icons` repository
- [ ] Icons in `baklava` repository will be removed and they will start fetching from `@trendyol/baklava-icons` package. For regular usage, there should be no difference from the user perspective.
- [ ] Icons in `baklava-react-native` repository will be removed and they will start fetching from `@trendyol/baklava-icons` package. For regular usage, there should be no difference from the user perspective.

## Technical details

Consuming new icon package in baklava web will be handled via our new ["custom registry" support](https://github.com/Trendyol/baklava/pull/555) in icon component. `@trendyol/baklava-icons` icon-set will be registered as `default` icon library.

**Comment by ogunb** [comment]
# Baklava Icons

The main issue is that each time a new icon is added or updated, users must update to the latest release to access the new icon, which might include other changes they do not need or want. Also our current setup involves maintaining icon libraries separately within different repositories for our web and React Native implementations. This has led to redundancy, versioning inconsistencies, and additional maintenance overhead.

### Decision

We will create a new repository named `baklava-icons` that will serve as the single source of truth for our icon assets. This repository will be published as an NPM package under the name `@trendyol/baklava-icons`.

### Details

- **Repository Creation**: A new repository, `baklava-icons`, will be created.
- **NPM Package**: The repository will be published to NPM under the scope `@trendyol/baklava-icons`.
- **Content**:
  - The package will contain only raw SVG files.
  - A comprehensive list of icons will be included.
- **Consumption**:
  - Consumers of the package will be responsible for handling the SVGs in their respective environments.
  - We will not provide React Native wrapper components.
  - SVG files can be consumed via jsDelivr or directly from the package.
- **Documentation**:
  - Icon documentation and tutorials will be updated accordingly.
  - Documentation will be maintained in the `baklava-icons` repository.

### Implications

- **Web**:
  - Icons in the `baklava` repository will be removed and replaced with imports from the `@trendyol/baklava-icons` package.
- **React Native**:
  - We will not support React/React Native wrappers in this package. Users will need to manage SVG integration in their projects. The stance on this may change in the future. Please provide feedback if you have an opinion on this.
