### ISSUE TITLE
Using tab component inside dialog

### ISSUE THREAD

**Issue by muratcorlu** [Trendyol/baklava#544]

**Comment by buseselvi** [comment]
Here is the [design link](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?node-id=1992%3A8280&t=kX0PHcrtxQDtdMmO-1), you can find it in the "Using Tab Component in Dialog" section.

**Comment by ozkersemih** [comment]
# Using Tab Component Inside Dialog
[Figma Link](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?type=design&node-id=1992-8280&mode=design&t=1Ueu9pdL12584bra-0)
We have specific design when we want to use tab component inside dialog component.

According to design we don't need padding for the are where **bl-tab-group** placed in **bl-dialog** component.

We achieve this behaviour by adding new slot inside bl-dialog component. We need to give specific name for this
slot so, this slot will only showed when we passed a child component with correct slot attribute name like below:

```html
<bl-dialog caption="Some title" open>
  <bl-tab-group slot="tab-group">
      <bl-tab name="test-1" slot="tabs" disabled>Disabled</bl-tab>
      <bl-tab name="test-2" slot="tabs" selected>Selected</bl-tab>
      <bl-tab name="test-3" slot="tabs">Tab</bl-tab>
    </bl-tab-group>
</bl-dialog>
```

After than we can give specific styling inside bl-dialog.css for bl-tag-group inside bl-dialog like below:
```css
::slotted(bl-tab-group) {
    display: block;
    transform: translateX(-1.5rem);
    width: calc(100% + 3rem);
}
```
