### ISSUE TITLE
Dialog should not close when we click somewhere outside the dialog

### ISSUE THREAD

**Issue by serkancetintas** [Trendyol/baklava#564]
Hello,
We save data with a form in the dialog. While filling out a form in the bl-dialog, the user can accidentally click outside the dialog and close the dialog.
Can it be optional to close the dialog when clicking outside the dialog ?

**Comment by serkancetintas** [comment]
I think closing on esc key and backdrop click can be optional. We can show confirmation when close buttons are clicked.

**Comment by muratcorlu** [comment]
Another option would be to have a new event that can be `defaultPrevented` to block closing dialog in specific flows defined by developer. Like this: https://shoelace.style/components/dialog?id=preventing-the-dialog-from-closing

**Comment by serkancetintas** [comment]
Yes, this option could work.

**Comment by muratcorlu** [comment]
@serkancetintas with version 2.2.0-beta.2, now you can track if your form has some changes and block closing dialog if it's not saved yet. Like:

```js
document.querySelector('bl-dialog').addEventListener('bl-dialog-request-close', (event) => {
  if (formIsDirty) {
    event.preventDefault();
    showWarningMessage();
  }
});
```
