### ISSUE TITLE
Contribution Guideline link on Storybook not working 

### ISSUE THREAD

**Issue by cagatay-usta** [Trendyol/baklava#568]
**Describe the bug**
As the storybook docs import from README.md, the link refers to './CONTRIBUTING.md' which works on github but on StoryBook it redirects to 'https://baklava.design/CONTRIBUTING.md' which naturally results in 404.

**To Reproduce**
1. Go to baklava.design
2. Click on 'For more information please check our [Contribution Guideline document]'
3. See error

**Expected behavior**
Ideally the link should refer depending on whether clicked from github or storybook. However as the markdown file is imported directly, I couldn't manage to add that logic without seperating the link between github and storybook docs.

**Proposed Solution**
Only working solution I could come up without creating the need to update both files seperately is to use absolute paths rather than relative, and have both github and storybook links avaliable:
`For more information please check our [Contribution Guideline document on GitHub](https://github.com/Trendyol/baklava/blob/next/CONTRIBUTING.md), or [on Storybook](https://baklava.design/?path=/docs/documentation-contributing-baklava-contribution-guideline--page).`

For more information please check our [Contribution Guideline document on GitHub](https://github.com/Trendyol/baklava/blob/next/CONTRIBUTING.md), or [on Storybook](https://baklava.design/?path=/docs/documentation-contributing-baklava-contribution-guideline--page).

**Screenshots**
404 page:

![baklava404](https://user-images.githubusercontent.com/124813114/236572938-126f7d3d-6657-4da2-a2c9-3fd5e10ee469.png)

working solution:

![baklavaWorkingSolution](https://user-images.githubusercontent.com/124813114/236574299-23a660e9-278a-41f1-a2fb-22ecad856902.png)

**Comment by onurravli** [comment]
Hello, fixed with #684.
