### ISSUE TITLE
Error state for checkbox

### ISSUE THREAD

**Issue by SeymaGuran** [Trendyol/baklava#571]
We want to show an error state  when a required checkbox isn't selected by the user. 
As in the example:

<img width="381" alt="image" src="https://user-images.githubusercontent.com/132919924/236855108-1edffc8b-db63-4279-aae2-91e45c28a2c3.png">

**Comment by muratcorlu** [comment]
Hi @SeymaGuran. Thanks for the report.

I think we missed error state when [we define UX of the checkbox](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?node-id=606-4458). @buseselvi Let's check this.

**Comment by buseselvi** [comment]
Hi, we updated the checkbox design document by adding the Required Checkbox section. You can see the design document [here](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?type=design&node-id=606%3A4458&t=l7sFIl420bMGXFwQ-1).  🚀

**Comment by onurtemiz** [comment]
Hi, as we talked on Slack, I have started working on this issue. However, I hit a blocker where I can't create the native validation message like in [this example](https://www.w3schools.com/JSREF/tryit.asp?filename=tryjsref_checkbox_required).  Is it possible to jump into a meeting to look into this issue?
<img width="422" alt="Screenshot 2023-07-18 at 13 13 01" src="https://github.com/Trendyol/baklava/assets/46234852/eee57f62-add4-489c-903f-aee59bee1f48">
