### ISSUE TITLE
Adding Autocomplete Component

### ISSUE THREAD

**Issue by MehmetCanBOZ** [Trendyol/baklava#573]
Can we add the **Autocomplete** component to Baklava, do you plan to add this component in your future work?

![Screen Shot 2023-05-09 at 11 23 51](https://user-images.githubusercontent.com/66769855/237040442-0614b40d-052c-42f1-b3ef-1ce3b47e23d4.png)

**Comment by muratcorlu** [comment]
Hi @MehmetCanBOZ, thanks for the suggestion.

We mentioned this (similar) functionality when we were discussing about adding search feature to select (#265). I think the feature you ask in your example screenshot is basically filtering in search, not auto completing. Auto completing should be something we need to consider adding to our “input” component, that accepts a text input but also can “suggest” user some  predefined values while they write it.

So, I think the feature you are asking here is on our plan and we are already working on that, as you can track it via #265. But auto-completing in input component is not something we considered yet, but probably it’ll come to the table soon. @buseselvi
