### ISSUE TITLE
Spacing issues in Dialogs without title

### ISSUE THREAD

**Issue by muratcorlu** [Trendyol/baklava#581]
Dialogs without titles keep the empty space on top, that causes ugly result in some cases. We need to address this issue.

If we remove that empty space in case of no title given, then close button comes over content section.

Let's find the most flexible yet consistent solution for this issue.

**Comment by muratcorlu** [comment]
## Design Meeting Report

Date: 23.05.2023 14:00 GMT+3

Today we discussed about this and some dialog-related topics with design meeting attendees. Here are the conclusions:

* We decided to encourage everyone to always set a title for dialogs for usability and accessibility purposes. But once no title (caption) is defined, the space currently reserved for title will not be taken up. So content will go up.
* We'll add a "feature" slot for dialog to add media (an image, video, or maybe custom content) to the dialog on top of title. Visual considerations will be done by the design team.
* Dialog close button (Cross on top-right) will be positioned absolutely. Then in case of feature slot provided or there is no title, the close button will go over those contents.
* We'll add a dialog variant named "critical". Critical dialog will hide default close button and disable closing dialog by clicking backdrop and Esc key. In this case dialog would be closed only by the action buttons defined in Dialog. (Addresses #564, #454)
* In addition to item above, developer should able to prevent closing a dialog programmatically. (Addresses #564)
* We'll allow developers to customize content paddings of dialog. (Partially addresses #544)

**Comment by buseselvi** [comment]
Here is the [design documentation link](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?type=design&node-id=1992%3A8280&t=E8wULDVAUnoZCOwA-1) for Critical Dialog and Dialog without Title.

**Comment by leventozen** [comment]
Since we don't implement this feature, I am closing this.
