### ISSUE TITLE
There is always a scrollbar showing up for the bl-tab on Windows

### ISSUE THREAD

**Issue by umitkucuk** [Trendyol/baklava#582]
**Describe the bug**
There is always a scrollbar showing up for the bl-tab on Windows.

**To Reproduce**
View the bl-tab component on Windows.

**Expected behavior**
The scrollbar should be visible only when needed.

**Screenshots**
![image](https://github.com/Trendyol/baklava/assets/24843599/9f76f460-a048-46c2-92d7-f58b0d7ac464)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 113.0

**Comment by muratcorlu** [comment]
Hi @umitkucuk. Thanks for reporting. Do you want to make a PR for that?

Also, it's sad we missed this :( I'll create an issue to address testing our elements on Windows.

**Comment by umitkucuk** [comment]
Hi @muratcorlu. Sure, I will be working on it.
