### ISSUE TITLE
Progress Indicator Color CSS Variable

### ISSUE THREAD

**Issue by CagriAldemir** [Trendyol/baklava#599]
We need different colors on Progress Indicator component. Can we add css variables for default progress indicator and failed progress indicator?

The design that we want to make is below;

![Ekran Resmi 2023-05-25 17 41 38](https://github.com/Trendyol/baklava/assets/8038704/1ace45aa-e789-4212-9349-b8f5c83d5d67)

**Comment by muratcorlu** [comment]
Actually, they are already variables: `--bl-color-success` and `--bl-color-danger`. For your use-case you can customise the colors as below:

```html
<style>
.rate-4-progress { --bl-color-success: <some-color>; }
.rate-3-progress { --bl-color-success: var(--bl-color-warning); }
.rate-2-progress { --bl-color-success: <some-color>; }
.rate-1-progress { --bl-color-success: var(--bl-color-danger); }
</style>

<bl-progress-indicator value="68" max="123"></bl-progress-indicator>
<bl-progress-indicator value="21" max="123" class="rate-4-progress"></bl-progress-indicator>
<bl-progress-indicator value="15" max="123" class="rate-3-progress"></bl-progress-indicator>
<bl-progress-indicator value="11" max="123" class="rate-2-progress"></bl-progress-indicator>
<bl-progress-indicator value="8" max="123" class="rate-1-progress"></bl-progress-indicator>
```

So you can override color variables in the scope of a single progress indicator. Does this make sense?

**Comment by muratcorlu** [comment]
@CagriAldemir Please consider re-opening the issue if you still need help.
