### ISSUE TITLE
[Feature Request]: Date Input min/max Props

### ISSUE THREAD

**Issue by CagriAldemir** [Trendyol/baklava#612]
### Describe the problem or use case

Currently there is no date input in baklava. But when we give date as input type, we can use native date as input. However, at this point, we cannot give the min and max props that we give to the native date inputs. Because when we give, the value given is cast to number and the value is converted to NaN.

### Proposed solution

Making the min and max props also accept the `YYYY-MM-DD` pattern.

**Comment by AykutSarac** [comment]
Interesting, I've used date as type at couple of places with no issues. Could you give more example & provide details to investigate further?

**Comment by CagriAldemir** [comment]
> Interesting, I've used date as type at couple of places with no issues. Could you give more example & provide details to investigate further?

When I use the input like this;

```html
<bl-input type="date" min="2023-07-10" max="2023-12-31" />
```

`min` and `max` attributes of input that inside shadow dom have `NaN` value. So, I cannot use `min` `max` attributes.

**Comment by AykutSarac** [comment]
Weird indeed, works fine on React project but it transforms min/max attributes to NaN in vanilla JS.

**Comment by AykutSarac** [comment]
Apparently it was min and max attribute's `type` that parsing it as number and converting it to NaN as a result. I've opened a PR to solve this. #651
