### ISSUE TITLE
[BUG]: Tooltip alignment

### ISSUE THREAD

**Issue by Enes5519** [Trendyol/baklava#622]
### Issue description

1. Create flex layout with `align-items: center`.
2. Add tooltip inside

### Media & Screenshots

<img width="480" alt="image" src="https://github.com/Trendyol/baklava/assets/10272532/e7d9f3bc-466f-49c1-b175-60f4bb52ab42">

### Baklava Version

2.2.0-beta.2

### Operating system

- OS: [e.g. iOS]: MacOS
- Browser [e.g. chrome, safari]: firefox

- Any other details...

### Priority this issue should have

Medium (should be fixed soon)

### Please review the checkboxes that are applicable.

- [ ] This issue is directly related to React

**Comment by muratcorlu** [comment]
I think this is related to #586. There are some UI effects of that change but once we merge it, I expect this issue will be fixed as well.

**Comment by Enes5519** [comment]
https://jsfiddle.net/enes5519/m0pja9dq/
