### ISSUE TITLE
Baklava Roadmap

### ISSUE THREAD

**Issue by leventozen** [Trendyol/baklava#64]
**Baklava Project Tasks List**

ref #63

- [x] #68
- [x] #78 
- [x] #71 
- [x] #76
- [x] #77 
- [ ] Documentation
  - [x] #69
  - [ ] #73
  - [x] #74 
  - [x] #89
  - [x] #228
  - [x] #229
  - [x] #224
  - [x] #230
  - [x] #231
  - [x] #235 
- [x] #65
- [x] #95
- [x] #96
- [x] #98
- [x] Implementation of publishing mechanism
	- [x] #67
	- [x] #79
	- [x] #80
	- [x] #81
	- [x] #82
	- [x] #83
- [ ] Design system
	- [x] #90
	- [ ] #91
	- [x] #92
	- [x] #93
	- [ ] #94
- [ ] Components
	- [ ] #84
	- [x] #85
	- [x] #86
	- [x] #87
	- [x] #88
	- [x] #136
	- [x] #135
	- [x] #145
	- [x] #134
	- [x] #239
	- [ ] #264 
	- [x] #137
	- [x] #138
	- [x] #130
	- [x] #139
	- [x] #140
	- [ ] #141
	- [ ] #142
	- [ ] #143
	- [ ] #144
- [ ] Technical Challenges
	- [x] #102
	- [ ] #103
	- [x] #104
	- [x] #124
	- [x] #146 
	- [x] #147 
	- [ ] #112 
	- [x] #113
	- [ ] #114

**Comment by muratcorlu** [comment]
I'm closing this in favor of using our [GitHub milestone](https://github.com/Trendyol/baklava/milestone/1) to track progress for first stable release.
