### ISSUE TITLE
[Feature Request]: <Can a table design be added to the Baklava Design System?>

### ISSUE THREAD

**Issue by vmutlu** [Trendyol/baklava#645]
### Describe the problem or use case

I could not find a component to be used for table design in Baklava Design System.

### Proposed solution

Adding table design to Baklava Design System

**Comment by muratcorlu** [comment]
Hi @vmutlu! Thanks for the request. Good news: We are working on it #142 😊

**Comment by vmutlu** [comment]
thank you @muratcorlu , take it easy.
