### ISSUE TITLE
[BUG]: Typo in storybook badge doc

### ISSUE THREAD

**Issue by mehmetranas** [Trendyol/baklava#668]
### Issue description

To reproduce the issue:

Go to the Storybook page.
Click on the "Badge" component and navigate to the "Documentation" section.
Scroll to the "Sizing Badges" section.
In the "Sizing Badges" section, you will notice a typographical error that states: "We have 3 size of buttons" instead of the correct statement "We have 3 sizes of badges."

### Baklava Version

2.2.0

### Priority this issue should have

Low (slightly annoying)

### Please review the checkboxes that are applicable.

- [ ] This issue is directly related to React

**Comment by onurravli** [comment]
Hello, I have opened a PR about this issue with [this commit](https://github.com/Trendyol/baklava/pull/684/commits/00c0e68a47733c7d1fd8726bb435898f2456b030). Thank you!
