### ISSUE TITLE
[BUG]: Can't prevent pressing Enter from input

### ISSUE THREAD

**Issue by Enes5519** [Trendyol/baklava#676]
### Issue description

I prevent keydown event but not working. I don't want to trigger form element.

### Baklava Version

2.2.0-beta.12

### Operating system

- OS: [e.g. iOS]: MacOS
- Browser [e.g. chrome, safari]: Firefox

- Any other details...

### Priority this issue should have

Low (slightly annoying)

### Please review the checkboxes that are applicable.

- [ ] This issue is directly related to React

**Comment by AykutSarac** [comment]
Can you try keydown capture event?

**Comment by Enes5519** [comment]
We can add a prop and include it in the condition [here](https://github.com/Trendyol/baklava/blob/next/src/components/input/bl-input.ts#L221), or we can **also** check whether the event is prevented or not, which I think will be the most effortless.

BTW I tried it didn't work.

**Comment by AykutSarac** [comment]
Which component did you attach the keydown capture event?

**Comment by Enes5519** [comment]
bl-input

**Comment by AykutSarac** [comment]
I've attached capture event to form and it works for me.

**Comment by Enes5519** [comment]
https://jsfiddle.net/enes5519/gp3k6bua/
