### ISSUE TITLE
[BUG]: Can't write tests with React

### ISSUE THREAD

**Issue by Enes5519** [Trendyol/baklava#681]
### Issue description

I could not run Baklava's React components on the testing library.

** Code **
```js
function App() {
  return (
    <main>
      <div>React Test</div>
      <BlButton>Merhaba</BlButton>
    </main>
  );
}
```

** Unit Test **
```js
import { expect, test } from "vitest";
import { render, screen, waitFor } from "@testing-library/react";
import React from "react";
import App from "./App";

test("should visible button", async () => {
  render(
    <React.Suspense fallback={<div>mantıklı</div>}>
      <App />
    </React.Suspense>
  );

  await waitFor(() => expect(screen.getByText("Merhaba")).toBeInTheDocument());
});
```

### Baklava Version

2.2.0

### Operating system

- OS: [e.g. iOS]: macOS Ventura 13.4
- Library: [React Testing Library](https://www.npmjs.com/package/@testing-library/react) 14.0.0
- Test Framework: Vitest 0.34.1

### Priority this issue should have

Medium (should be fixed soon)

### Please review the checkboxes that are applicable.

- [X] This issue is directly related to React

**Comment by muratcorlu** [comment]
@Enes5519 Can you also add the part how you import the `BlButton` and Baklava library in general to your code and the project?

**Comment by sametkabay** [comment]
@Enes5519 maybe this issue can solve your problem https://github.com/Trendyol/baklava/issues/577
