### ISSUE TITLE
Changing the Color of the Informational Component Variants

### ISSUE THREAD

**Issue by buseselvi** [Trendyol/baklava#685]
Informational component variants such as Informational Alerts and Informational Notifications shouldn't be the primary color. Because the primary color is usually the brand color. And brand colors can also be colors such as red, yellow, green. This may cause conflict between the informational and danger/warning/success variants. 

For our default theme, the primary color is the orange color. Orange does not have an informational meaning, and the color we use in the informational alert is very close to the warning variant colors. We did UX research on this topic and users were unable to distinguish between informational and warning variants.

<img width="604" alt="image" src="https://github.com/Trendyol/baklava/assets/106681486/52feb859-d0cb-432a-bc04-3000e50479a0">

Users also match the informational variant with the blue color that we don't have. When we looked for the best practice for our case we saw blue is also known as informational color. 

So, as the UX team, we are suggesting adding **Info Color** to our color palette for informational component variants. And for our default theme, this color should be blue due to research findings. 

<img width="845" alt="image" src="https://github.com/Trendyol/baklava/assets/106681486/c896e01a-2789-418d-a43e-5ad26345d706">
<img width="422" alt="image" src="https://github.com/Trendyol/baklava/assets/106681486/d0ddbdbc-34d0-46ce-892c-2c88e8f019c1">

**Comment by prathammpurohit** [comment]
Hey @muratcorlu, I would like to work on this issue.

May we discuss it further?

**Comment by muratcorlu** [comment]
Hi @prathammpurohit! Thanks for your interest. We considered this a breaking change and plan to release it with the next major version (v3), which we don't plan to have any time soon. Please consider other tasks if you are interested in contributing Baklava!

**Comment by prathammpurohit** [comment]
Cool!
