### ISSUE TITLE
[BUG]: Select placeholder not shown

### ISSUE THREAD

**Issue by AykutSarac** [Trendyol/baklava#719]
### Issue description

After upgrading from 2.3.0-beta.4 to 2.3.0-beta.5 Select's placeholder no longer visible.

### Media & Screenshots

<img width="376" alt="image" src="https://github.com/Trendyol/baklava/assets/47941171/848353e0-5dd4-42dc-9747-a56057deb578">

<img width="385" alt="image" src="https://github.com/Trendyol/baklava/assets/47941171/6932279c-2554-4efc-9e2d-0be76ab6c95e">

### Baklava Version

2.3.0-beta.5

### Operating system

- OS: [e.g. iOS]:
- Browser [e.g. chrome, safari]:

- Any other details...

### Priority this issue should have

Medium (should be fixed soon)

### Please review the checkboxes that are applicable.

- [ ] This issue is directly related to React

**Comment by muratcorlu** [comment]
Oh, my bad. This should be related with auto width work that I have done #706 . I'll have a look.

**Comment by muratcorlu** [comment]
It would be great to address those issues with a more generic solution like we mentioned in #299 and #463
