### ISSUE TITLE
[BUG]: bl-input type color width

### ISSUE THREAD

**Issue by 0o001** [Trendyol/baklava#723]
### Issue description

bl-input type color comes in a large size by default.

### Media & Screenshots

<img width="233" alt="image" src="https://github.com/Trendyol/baklava/assets/4294069/bf04bf07-8b00-4533-a7f7-7e7f7e654818">

### Operating system

- OS: [e.g. iOS]: macOS
- Browser [e.g. chrome, safari]: Safari and Chrome

- Any other details...

### Priority this issue should have

Low (slightly annoying)

### Please review the checkboxes that are applicable.

- [ ] This issue is directly related to React

**Comment by AykutSarac** [comment]
Input type color is not officially supported so this is rather a feature request than a bug report. I think there'd be a separate component for color picker, but likely it's at the bottom of our priority list for now.
