### ISSUE TITLE
[BUG]: rendering issue with logical operators in React

### ISSUE THREAD

**Issue by qraxiss** [Trendyol/baklava#730]
### Issue description

When i using logical or in two bl-button component, styles mixed.

```typescript
    const loading = isLoading && (
        <BlButton size="small" loading>
            Loading...
        </BlButton>
    )

    const isError = error && (
        <BlButton kind="danger" icon="warning">
            {error}
        </BlButton>
    )

    return (
        <div className="homepage">
            {isError || loading}

            <BlogList blogs={blogs} title="All Blogs" handleDelete={handleDelete} />
        </div>
    )
}
```

i expected error, but error contains ```loading``` prop.

### Media & Screenshots

<img width="444" alt="image" src="https://github.com/Trendyol/baklava/assets/92579832/4965d374-5b6a-4f4a-b866-98d011b0df46">

### Baklava Version

^2.2.0

### Operating system

- OS: [MacOS Ventura]:
- Browser [safari, chrome]:

```package.json```   
```json
{
  "dependencies": {
    "@trendyol/baklava": "^2.2.0",
    "axios": "^1.5.1",
    "bootstrap": "^5.3.2",
    "react": "^18.2.0",
    "react-bootstrap": "^2.9.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "@vitejs/plugin-react": "^4.0.3",
    "eslint": "^8.45.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.3",
    "typescript": "^5.0.2",
    "vite": "^4.4.5"
  }
}
```

### Priority this issue should have

High (immediate attention needed)

### Please review the checkboxes that are applicable.

- [X] This issue is directly related to React

**Comment by Enes5519** [comment]
If you are re-rendering the same component conditionally in React, you must pass a 'key.' Therefore, you can resolve it by passing the 'key' attribute.

**Comment by muratcorlu** [comment]
Your code example is not very detailed, I couldn't reproduce the issue. A running example that reproduces the issue would be very helpful.

But apparently in your case loading and error buttons are somehow using the same instance and error button is not setting `loading` to `false` because it's not set explicitly. Either using `key` as @Enes5519 already mentioned (to render a separate button component for each) or setting `loading={false}` in error button explicitly would mitigate the issue.

**Comment by qraxiss** [comment]
Thank you very much; both of your answers were very helpful. @muratcorlu @Enes5519 

Setting ```loading=false``` and ```key="sa"``` (as Enes 🙂) solved the problem.

Even though the error was related to React rather than the library, I appreciate your help.

**Comment by AykutSarac** [comment]
Reopening the issue as this could be potentially still valid as per our experience today.
