### ISSUE TITLE
[Feature Request]: Dialog title is too long

### ISSUE THREAD

**Issue by Enes5519** [Trendyol/baklava#737]
### Describe the problem or use case

The Dialog caption is currently **nowrap**, but this can be ugly in some cases and it may be necessary to increase it to 2 lines.

**Actual**
<img width="676" alt="image" src="https://github.com/Trendyol/baklava/assets/10272532/90eb8a33-df49-40c5-9bf0-8b934b9f879a">

**Expected**
<img width="401" alt="image" src="https://github.com/Trendyol/baklava/assets/10272532/2036ac12-4ca3-4e28-abf0-0b131db0d08a">

### Proposed solution

We can add a line clamp and keep its value in a css variable.

https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp

### Alternatives considered

We can add the ability to adjust the dialog width. We can also remove Nowrap from the caption.

**Comment by umutbozdag** [comment]
Hi @Enes5519, I would like to work on this but when I start storybook server, I can't see any components related to Baklava. This is the errors I get:
![image](https://github.com/Trendyol/baklava/assets/43722871/2b3f2d07-21c8-4e21-ba7f-8be1ce78268c)

Do you have an idea how can I fix this?

**Comment by leventozen** [comment]
Hey @umutbozdag, I couldn't reproduce your issue in my local environment. Can you give us more details about how to run the application, your npm and node version's and your browser and browser version etc.
