### ISSUE TITLE
[Feature Request]: Add BlSwitch label

### ISSUE THREAD

**Issue by AykutSarac** [Trendyol/baklava#747]
### Describe the problem or use case

Switch component needs a label similar to checkbox

### Proposed solution

Accept label as children/slot and set aria-label same as the children

```jsx
<BlSwitch>
  Enable dark mode
</BlSwitch>
```

**Comment by 0o001** [comment]
I'm sorry, a lot of tags were created due to my little mistake.

**Comment by ogunb** [comment]
Closed by https://github.com/Trendyol/baklava/pull/754
