### ISSUE TITLE
[Feature Request]: Custom component as SelectOption

### ISSUE THREAD

**Issue by erkanzileli** [Trendyol/baklava#751]
### Describe the problem or use case

I want to use a custom component as a SelectOption because I want to add badges to the elements

### Proposed solution

It'd be nice if I'll be able to provide `children` in the SelectOption

### Alternatives considered

If you have any alternatives for this, it'd be nice

**Comment by leventozen** [comment]
@buseselvi what do you think about this? We may consider adding badges as a functionality to our select options rather than supporting custom component?

**Comment by buseselvi** [comment]
Hi, can you share an image of the example? @erkanzileli

**Comment by ogunb** [comment]
If I didn't misunderstand, it should already be possible.

https://codesandbox.io/p/sandbox/determined-wood-kgp3s9?file=%2Fsrc%2FApp.vue%3A20%2C15

**Comment by ogunb** [comment]
This issue should be solved with https://github.com/Trendyol/baklava/pull/766. Feel free to reopen it, if you have any concerns over it.
