### ISSUE TITLE
[BUG]: bl-select with bl-tooltip issue

### ISSUE THREAD

**Issue by omrumbakitemiz** [Trendyol/baklava#764]
### Issue description

The `bl-select` component always shows all the textContent inside the `bl-select-option`

Let's say you have a `bl-select-option` with `bl-tooltip` in it. When that option is selected in `bl-select`, the text inside the tooltip that appears when hovered also appears as selected in the select.

```
<bl-select class="w-96" size="large" placeholder="Kupon Seçiniz" clearable>
  <bl-select-option v-for="coupon in coupons" :key="coupon.id" :value="coupon.id">
    <div class="flex flex-row items-center gap-2">
      <div>{{ coupon.name }}</div>

      <bl-tooltip>
        <bl-button slot="tooltip-trigger" icon="settings" variant="tertiary" kind="neutral" label="Settings"></bl-button>
        Select this coupon for better engagement!
      </bl-tooltip>
    </div>
  </bl-select-option>
</bl-select>
```
![Screenshot 2024-01-08 at 5 02 09 PM](https://github.com/Trendyol/baklava/assets/12871066/80366c2d-cdd0-4845-8dd6-6cc323406265)

Reproduction of the issue:
https://stackblitz.com/edit/vitejs-vite-yy9ud2?file=src%2FApp.vue

### Media & Screenshots

https://github.com/Trendyol/baklava/assets/12871066/67ac9d1a-8e38-4a17-9e89-a5d05401f4b9

### Baklava Version

2.3.0-beta.10

### Operating system

- OS: macOS 14.2.1 (23C71)
- Browser: Chrome, Firefox

### Priority this issue should have

Medium (should be fixed soon)

### Please review the checkboxes that are applicable.

- [ ] This issue is directly related to React

**Comment by mustafafrw** [comment]
Hello,

I have a solution for this issue. We can add an attribute like `option-label-query` to bl-select. If there is a value, we can run querySelector with that value. In this way `bl-select-option` can be customizable as desired. After this solution your code will change like this.

```
<bl-select class="w-96" size="large" placeholder="Kupon Seçiniz" clearable option-label-query=".option-label">
  <bl-select-option v-for="coupon in coupons" :key="coupon.id" :value="coupon.id">
    <div class="flex flex-row items-center gap-2">
      <div class="option-label">{{ coupon.name }}</div>

      <bl-tooltip>
        <bl-button slot="tooltip-trigger" icon="settings" variant="tertiary" kind="neutral" label="Settings"></bl-button>
        Select this coupon for better engagement!
      </bl-tooltip>
    </div>
  </bl-select-option>
</bl-select>
```

What do you guys think about this solution?

**Comment by omrumbakitemiz** [comment]
Hey, I also have a similar solution for this [here](https://github.com/Trendyol/baklava/pull/765), I added an option called `option-label` to `bl-select-option` and on the `bl-select` I changed `inputTemplate` function like this 

```
// old way
${this._selectedOptions.map(item => html`<li>${item.textContent}</li>`)}

// new way
${this._selectedOptions.map(item => html`<li>${item.getAttribute('option-label') || item.textContent}</li>`)}
```

The PR is here It is just for sharing my solution.
https://github.com/Trendyol/baklava/pull/765
