### ISSUE TITLE
[Feature Request]: extending drawer width

### ISSUE THREAD

**Issue by alpgokcek** [Trendyol/baklava#767]
### Describe the problem or use case

When using the Baklava in scenario where i need Drawer, I encountered issues with extending the width of it. I want to make it 80vw but it is set to 424px.

### Proposed solution

We can make it extendible with a variable

**Comment by leventozen** [comment]
what do you think? @buseselvi

**Comment by buseselvi** [comment]
I think we can extend the variants 👌🏻 Maybe we can do it like we did in the Dialog Component, the width of it can depend on the content. Or there are examples of size variants like small, medium, and large for drawers we can do that, too. Let's talk about it in the design meeting. @leventozen @alpgokcek

**Comment by buseselvi** [comment]
We agreed that the Drawer width can be changed by the content, so we can add the free width feature. By default, its width should stay the same (424px). @alpgokcek
