### ISSUE TITLE
[BUG]: The Baklava logo does not appear clearly in the dark theme.

### ISSUE THREAD

**Issue by imhalid** [Trendyol/baklava#786]
### Issue description

The Baklava logo in the README file does not appear clearly in dark mode
The text color may be light.

### Media & Screenshots

<img width="950" alt="Screenshot 2024-01-26 at 14 05 27" src="https://github.com/Trendyol/baklava/assets/40598819/afa9251d-c1f5-44e0-8eee-ef71b79f84a2">

### Priority this issue should have

Low (slightly annoying)

### Please review the checkboxes that are applicable.

- [ ] This issue is directly related to React

**Comment by imhalid** [comment]
this code solves the issue

```html
<p align="center">
  <picture>
    <source width="200" media="(prefers-color-scheme: dark)" srcset="https://github.com/Trendyol/baklava/assets/40598819/5a2d9304-8422-46f5-8d70-948e24100fb5">
    <img width="200" alt="Shows an illustrated sun in light color mode and a moon with stars in dark color mode." src="https://user-images.githubusercontent.com/127687/233114483-c5b0a8e7-c072-4ced-a7b5-76bce1be4b21.svg">
  </picture>
</p>
```

**Comment by fatihhayri** [comment]
The "BAKLAVA" of Dark mode may be  text color white. @buseselvi

**Comment by buseselvi** [comment]
I agree, here I added the dark mode bl-logo. You can use it 🙏 

![Uploading bl_logo_dark.png…]()

**Comment by imhalid** [comment]
links not working :/ @buseselvi

**Comment by buseselvi** [comment]
I share the design file link, can you export from there? I couldn't share it as a PNG file, I don't know why 😔

**Comment by imhalid** [comment]
Yes, I exported it from figma and opened a PR #790, thank you for your support.
