### ISSUE TITLE
[BUG]: bl-select disabled item count

### ISSUE THREAD

**Issue by AykutSarac** [Trendyol/baklava#792]
### Issue description

Selected item count is shown in black color despite being disabled

### Media & Screenshots

![image](https://github.com/Trendyol/baklava/assets/47941171/dcc52377-1e00-4eff-86c8-dd5342af7d9b)

### Priority this issue should have

Low (slightly annoying)

### Please review the checkboxes that are applicable.

- [ ] This issue is directly related to React

**Comment by erbilnas** [comment]
Could this be an intentional decision? @buseselvi I think we need your thoughts here.

**Comment by buseselvi** [comment]
No, it is not intentional. It should be fixed to `--bl-color-neutral-light` 🥲
