### ISSUE TITLE
[BUG]: searchable select component default empty list

### ISSUE THREAD

**Issue by oemolla** [Trendyol/baklava#794]
### Issue description

When we click on the bl-select component to search, an orange line appears.

### Media & Screenshots

![Screenshot 2024-02-06 at 11 45 36 AM](https://github.com/Trendyol/baklava/assets/12650525/e16643f1-0160-45fc-88cf-1eef481865ee)

### Priority this issue should have

High (immediate attention needed)

### Please review the checkboxes that are applicable.

- [ ] This issue is directly related to React

**Comment by erbilnas** [comment]
Have you attempted to provide a `SelectOption`? It will be displayed in that manner if there are no options available for the select.

**Comment by oemolla** [comment]
SelectOption will be created once the search process concludes. Initially, there are no SelectOptions during the first render because the data is empty.

**Comment by erbilnas** [comment]
You should wait for the data fetching to complete before attempting to render, ensuring successful option rendering or you will attempt to re-render the select option

**Comment by oemolla** [comment]
To start the data fetching process, I need to click selected and perform the action. The error happens right at this moment.

**Comment by erbilnas** [comment]
We are not currently supporting API fetching with search functionality, so you should handle the data manually. At the moment, providing a slot element to `bl-select` when fetching data can be worked around using the following approach:

```
<bl-select
     multiple
     search-bar
     search-bar-placeholder="Arama yapabilirsiniz"
>
    // your custom element 
</bl-select>
```

**Comment by oemolla** [comment]
I am currently using this method. I just wanted to let you know because component trying to create an option with empty data.

**Comment by AykutSarac** [comment]
This appears to be a UI scenario, so we can seek assistance from @buseselvi in this matter. What should be shown to the user if no selection option has been added?

**Comment by buseselvi** [comment]
We shouldn't show the select popover / a line like in the image above if the popover is empty, we should show only the select input. Let's fix it 🚀
