### ISSUE TITLE
[BUG]: border-top is not coming correctly in BlInput label animation

### ISSUE THREAD

**Issue by utqkaba** [Trendyol/baklava#806]
### Issue description

When we click on the input field, the label should go to the upper left corner and the border of the upper left corner should disappear. But the middle of the top border disappears.

### Media & Screenshots

<img width="242" alt="Screenshot 2024-02-29 at 17 22 27" src="https://github.com/Trendyol/baklava/assets/48655033/1b7cd6b2-27b1-42c3-a3bf-80ec96061d0e">
<br>
<br>
Incorrect input label and border;
<br>
<img width="244" alt="Screenshot 2024-02-29 at 17 22 31" src="https://github.com/Trendyol/baklava/assets/48655033/335f230c-b4f6-4276-b7fd-bf9b19b3c30e">
<br>
<br>
Correct input label and border;
<br>
<img width="228" alt="Screenshot 2024-02-29 at 17 37 02" src="https://github.com/Trendyol/baklava/assets/48655033/ed7026ba-4d78-4f80-81bd-fcda3053ac71">

### Operating system

- OS: [e.g. iOS]:
- Browser [e.g. chrome, safari]:

- Any other details...

### Priority this issue should have

Low (slightly annoying)

### Please review the checkboxes that are applicable.

- [ ] This issue is directly related to React

**Comment by fatihhayri** [comment]
Hi @utqkaba, 

I tried a similar sample but did not view your bug. 


https://github.com/Trendyol/baklava/assets/759429/8ac4c83d-b6c5-47f4-90ca-8bdbe3abaae3

**Comment by fatihhayri** [comment]
Not at all
