### ISSUE TITLE
Add Custom CSS Properties for Border Radius, Style, and Color to bl-button

### ISSUE THREAD

**Issue by MehmetCanBOZ** [Trendyol/baklava#812]
Description
In split button design [Figma](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?node-id=2161%3A9122), we need to add some CSS custom properties for borders to match with the design.

This issue aims to enhance the bl-button component's styling flexibility by introducing three new CSS custom properties:

* --bl-button-border-radius
* --bl-button-border-style
* --bl-button-border-color

These properties will allow developers to more easily customize the appearance of **bl-button** components to fit the design requirements of their projects without modifying the component's internal CSS or structure.

**Comment by erbilnas** [comment]
We don't need these attributes because we already have four styles: Default, Neutral, Success, and Danger. We want to enforce strictness in order to maintain consistency within the design system.

**Comment by MehmetCanBOZ** [comment]
* Is it possible to change the border radius of buttons?

* For border style, in the secondary type of split button, the primary button and dropdown button are adjacent and to avoid overlapping borders each other, I think that if I give the "none" left border of the dropdown button It solves the issue.

* for border color, in the disabled type of split button, there is a divider between the primary button and the dropdown button. I think that if I give the specific border color to the right border of the split button It solves the issue. 

You are right, maybe I can add a divider for the last one, but for the other ones, we can talk if they are necessary or not.

**Comment by erbilnas** [comment]
- No, it isn't.
- The border style shouldn't be changed by the developer, so I believe your solution is appropriate.
- The button and the dropdown handler each have separate disabled attributes, so they should be considered as three different scenarios.

**Comment by erbilnas** [comment]
You could consider one of them as the new button inherited from our `bl-button`, while the other is an already existing component of `bl-dropdown`.
