### ISSUE TITLE
[Feature Request]: <Adding Critical Dialog Variant to Dialog Component>

### ISSUE THREAD

**Issue by buseselvi** [Trendyol/baklava#853]
### Describe the problem or use case

If a dialog is critical, we want to prevent closing the dialog (including the keyboard (esc), backdrop, and close button)  and hide the close button, since no closing action can be taken from there. In this case, action can only be taken from the buttons in the dialog footer.

[design documentation](https://www.figma.com/file/RrcLH0mWpIUy4vwuTlDeKN/Baklava-Design-Guide?type=design&node-id=1992%3A8280&mode=design&t=rWKfrqo4mKogcv6i-1)

<img width="1227" alt="image" src="https://github.com/Trendyol/baklava/assets/106681486/c0f92089-a16c-4d5c-9523-55fd55446679">

**Comment by ogunb** [comment]
Closed by https://github.com/Trendyol/baklava/pull/870. It will be release on 3.2.0.
