### ISSUE TITLE
[BUG]: The versions of deployments made for the beta version should not lag the main versions

### ISSUE THREAD

**Issue by erbilnas** [Trendyol/baklava#892]
### Issue description

- Open the "Releases" section

- Review the current situation:
  - We have already released version v3.1.0
  - However, our next branch is still following the 3.0-beta-x versioning pattern

- Action required:
  - Update the next branch versioning to align with the latest release
  - The new versioning should follow the 3.1-beta-x pattern or prepare for 3.2-beta-x, depending on your versioning strategy

Ensure that future beta versions are always aligned with or ahead of the main release versions

### Priority this issue should have

High (immediate attention needed)

### Please review the checkboxes that are applicable.

- [ ] This issue is directly related to React

**Comment by muratcorlu** [comment]
You just need to merge `main` branch to `next` just after every stable releases. Then stable release tag will be included in `next` branch as well, so semantic-release can see the latest release when generating beta release tag on `next` branch ;)
