### ISSUE TITLE
[BUG]: Checkbox position broken 

### ISSUE THREAD

**Issue by MrAkblt** [Trendyol/baklava#900]
### Issue description

You can see that when you scroll up and down the checkbox also scrolls. I think the checkbox needs a CSS class named dirty, but such a class does not appear in Chrome Dev Tools. I solved the problem by adding `position: relative` to the first checkbox

![Screenshot 2024-07-31 at 19 12 55](https://github.com/user-attachments/assets/085cdbca-2ad3-41a2-a54a-7e245d57233b)

https://github.com/user-attachments/assets/087f2b02-8ff9-40e0-8215-5b76471bda49

### Baklava Version

3.1.0

### Operating system

- OS: [e.g. iOS]: MacOS
- Browser [e.g. chrome, safari]: Chrome

### Priority this issue should have

Medium (should be fixed soon)

### Please review the checkboxes that are applicable.

- [ ] This issue is directly related to React

**Comment by ogunb** [comment]
Thank you for your report.

The issue has been addressed in https://github.com/Trendyol/baklava/issues/895 and is available in the beta release. It will be included in the 3.2.0 release.

Release: https://github.com/Trendyol/baklava/releases/tag/v3.0.0-beta.27 (Ignore the versioning, it will be fixed.)
