### ISSUE TITLE
[BUG]: <SyntaxError: Unexpected identifier 'assert' in generate-react-exports.js>

### ISSUE THREAD

**Issue by mryunt02** [Trendyol/baklava#936]
### Issue description

Hello,

I encountered an issue when running npm run test in the Baklava project. The following error occurs:
```
`> @trendyol/baklava@0.0.0-dev pretest
> npm run build

> @trendyol/baklava@0.0.0-dev build
> del-cli dist/ && npm run analyze && npm run generate-react-exports && tsc --emitDeclarationOnly && node scripts/build.js && npm run generate-vue-types

> @trendyol/baklava@0.0.0-dev analyze
> cem analyze

[11:46:16 PM] @custom-elements-manifest/analyzer: Created new manifest.

> @trendyol/baklava@0.0.0-dev generate-react-exports
> node scripts/generate-react-exports.js

file:///Users/bugrahanyunt/Developer/baklava/scripts/generate-react-exports.js:6
import prettierConfig from "../.prettierrc.json" assert { type: "json" };
                                                 ^^^^^^

SyntaxError: Unexpected identifier 'assert'
    at compileSourceTextModule (node:internal/modules/esm/utils:337:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:166:18)
    at callTranslator (node:internal/modules/esm/loader:437:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:443:30)
    at async ModuleJob._link (node:internal/modules/esm/module_job:106:19)

Node.js v22.9.0
`
```
To troubleshoot, I replaced "assert { type: "json" }" with "with { type: "json" }" in generate-react-exports.js. This allowed me to run the tests successfully, but I cannot commit this change.

Could you please provide guidance on how to resolve this issue?

Thank you.

### Operating system

- Browser [e.g. chrome, safari]: chrome
- Node.js version: 22.9.0
- npm version: 10.8.3
- Operating system: macOS

### Priority this issue should have

Low (slightly annoying)

### Please review the checkboxes that are applicable.

- [ ] This issue is directly related to React

**Comment by erbilnas** [comment]
You can use it with Node 20, it seems that Node 22 is likely causing some issues
